In [1]:
# !brew install lightgbm

In [2]:
import subprocess; result = subprocess.run(['pip3', 'install', 'ipython-autotime'], capture_output=True)
print(f"There was a problem installing the package.\nError output:\n{result.stderr.decode('utf-8')}") if result.returncode != 0 else print("Package installed successfully.")

Package installed successfully.

In [3]:
%load_ext autotime

time: 138 µs (started: 2024-04-06 22:21:06 -07:00)

In [4]:
import sys
source_directory = "/opt/homebrew/bin"
sys.path.append(source_directory)

source_directory = "/opt/homebrew/Cellar"
sys.path.append(source_directory)

import sys
source_directory = "/Users/pauljacob/Library/Python/3.9/lib/python/site-packages"
sys.path.append(source_directory)

time: 365 µs (started: 2024-04-06 22:21:06 -07:00)

In [5]:
import os
import gc
from glob import glob
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd
import polars as pl

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import StratifiedGroupKFold
from sklearn.base import BaseEstimator, ClassifierMixin

import lightgbm as lgb

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

time: 2.09 s (started: 2024-04-06 22:21:06 -07:00)

In [6]:
import time


from IPython.core.display import display, HTML
display(HTML("<style>.container { width:99.9% !important; }</style>"))
pd.options.display.max_columns = 3999
pd.options.display.max_rows = 999

pd.set_option('display.max_colwidth', None)
pd.options.display.max_info_columns = 3999

/var/folders/77/y4hv4_s9751293nzv4yrfrtm0000gn/T/ipykernel_4499/3040381397.py:4: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML

time: 2.43 ms (started: 2024-04-06 22:21:08 -07:00)

### Pre-Fitted Voting Model

In [7]:
class VotingModel(BaseEstimator, ClassifierMixin):
    def __init__(self, estimators):
        super().__init__()
        self.estimators = estimators
        
    def fit(self, X, y=None):
        return self
    
    def predict(self, X):
        y_preds = [estimator.predict(X) for estimator in self.estimators]
        return np.mean(y_preds, axis=0)
    
    def predict_proba(self, X):
        y_preds = [estimator.predict_proba(X) for estimator in self.estimators]
        return np.mean(y_preds, axis=0)

time: 513 µs (started: 2024-04-06 22:21:08 -07:00)

### Pipeline

### Automatic Aggregation

### File I/O

### Feature Engineering

### Configuration

### Train Files Read & Feature Engineering

In [8]:
# import pandas as pd

# def drop_null_columns(df, threshold=0.95):
#     null_threshold = threshold * len(df)
    
#     columns_to_drop = [col for col in df.columns if df[col].isnull().sum() > null_threshold]
    
#     df = df.drop(columns=columns_to_drop)
    
#     return df

time: 286 µs (started: 2024-04-06 22:21:08 -07:00)

In [9]:
#i.e. This refers to the date when a decision was made regarding the approval of the loan.

time: 196 µs (started: 2024-04-06 22:21:08 -07:00)

In [10]:
# class Pipeline:
#     @staticmethod
#     def set_table_dtypes(df):
#         for col in df.columns:
#             if col in ["case_id", "WEEK_NUM", "num_group1", "num_group2"]:
#                 df.loc[:, col] = df.loc[:, col].astype('int32')
#             elif col in ["date_decision"]:
#                 df.loc[:, col] = pd.to_datetime(df.loc[:, col]) #.astype('datetime64[ns]') #with_columns(pl.col(col).cast(pl.Date))
#             elif col[-1] in ("P", "A"):
#                 df.loc[:, col] = df.loc[:, col].astype('float64') #with_columns(pl.col(col).cast(pl.Float64))
#             elif col[-1] in ("M",):
#                 df.loc[:, col] = df.loc[:, col].astype('object') #.astype('string') #with_columns(pl.col(col).cast(pl.String))
#             elif col[-1] in ("D",):
#                 df.loc[:, col] = pd.to_datetime(df.loc[:, col]) #.astype('datetime64[ns]') #with_columns(pl.col(col).cast(pl.Date))            

#         return df
    
#     @staticmethod
#     def handle_dates(df):
#         '''Edit date to number of days before the loan approval/refusal/denial decision date'''
#         for col in df.columns:
#             if col[-1] in ("D",):
#                 df.loc[:, col] = df.loc[:, col] - df.loc[:, 'date_decision'] #.with_columns(pl.col(col) - pl.col("date_decision"))
#                 df.loc[:, col] = df.loc[:, col].astype('timedelta64[D]') #df = df.with_columns(pl.col(col).dt.total_days())
#                 #with_columns(pl.col(col).cast(pl.Float32))
                
#         df = df.drop("date_decision", "MONTH")

#         return df
    
#     @staticmethod
#     def filter_cols(df):
#         for col in df.columns:
#             if col not in ["target", "case_id", "WEEK_NUM"]:
#                 isnull = df[col].isnull().mean()

#                 if isnull > 0.95:
#                     df = df.drop(columns=col)

#         for col in df.columns:
#             if (col not in ["target", "case_id", "WEEK_NUM"]) & (df[col].dtype == object):
#                 freq = df[col].nunique()

#                 if (freq == 1) | (freq > 200):
#                     df = df.drop(columns=col)

#         return df



    
    
# #V-- what does this Aggregator class do??? why do the methods return "expr_max"???? Is this feature engineering??

# class Aggregator:
#     @staticmethod
#     def num_expr(df):
#         '''P is for Transform DPD (Days past due);
#            A is for Transform amount
#         '''
#         cols = [col for col in df.columns if col[-1] in ("P", "A")]

#         return {col:'max' for col in cols}
   

#     @staticmethod
#     def date_expr(df):
#         '''D is for Transform date
#         '''
#         cols = [col for col in df.columns if col[-1] in ("D",)]

#         return {col:'max' for col in cols} #expr_max = [pl.max(col).alias(f"max_{col}") for col in cols]

#     @staticmethod
#     def str_expr(df):
#         '''M is for  Masking categories
#         '''
#         cols = [col for col in df.columns if col[-1] in ("M",)]
        
#         return {col:'max' for col in cols} #expr_max = [pl.max(col).alias(f"max_{col}") for col in cols]

#     @staticmethod
#     def other_expr(df):
#         '''T is for Unspecified Transform
#            L is for Unspecified Transform
#         '''
#         cols = [col for col in df.columns if col[-1] in ("T", "L")]
        
#         return {col:'max' for col in cols} #expr_max = [pl.max(col).alias(f"max_{col}") for col in cols]

    
#     @staticmethod
#     def count_expr(df):
#         cols = [col for col in df.columns if "num_group" in col]

#         return {col:'max' for col in cols} #expr_max = [pl.max(col).alias(f"max_{col}") for col in cols]
        

#     @staticmethod
#     def get_exprs(df):
#         return {**Aggregator.num_expr(df),
#                 #**Aggregator.date_expr(df), 
#                 #**Aggregator.str_expr(df), 
#                 **Aggregator.other_expr(df),
#                 **Aggregator.count_expr(df)}

    
#     @staticmethod    
#     def get_cols_dictionary(df):
#         exprs = Aggregator.get_exprs(df)
#         cols = exprs.keys()
#         cols_dictionary = {f'{col}':f'{exprs[col]}_{col}' for col in cols}
#         print(f"cols_dictionary: {cols_dictionary}")
#         return cols_dictionary



# ####v--- is read_file and read_files performing feature engineering??? or just reading in the data???

# def read_file(path, depth=None):
#     '''read in the file;
#        set the data type by column name or suffix
#     '''
#     df = pd.read_csv(path)
#     df = df.pipe(Pipeline.set_table_dtypes)
    
#     if depth in [1, 2]:
#         df = df.groupby("case_id").agg(Aggregator.get_exprs(df)).rename(columns=Aggregator.get_cols_dictionary(df)) #df = df.groupby("case_id").agg(Aggregator.get_exprs(df))
    
#     return df

# def read_files(regex_path, depth=None):
#     chunks = []
#     for path in glob(str(regex_path)):
#         df = pd.read_csv(path)
#         df = df.pipe(Pipeline.set_table_dtypes)
        
#         if depth in [1, 2]:
# #             print(print(f"df.shape: {df.shape}"))
# #             print(f"df: {df}")
# #             print(f"len(Aggregator.get_exprs(df)): {len(Aggregator.get_exprs(df))}")
# #             print(f"Aggregator.get_exprs(df): {Aggregator.get_exprs(df)}")
# #             print(f"len(Aggregator.get_cols_dictionary(df)): {len(Aggregator.get_cols_dictionary(df))}")
# #             print(f"Aggregator.get_cols_dictionary(df): {Aggregator.get_cols_dictionary(df)}")
#             df = df.groupby("case_id").agg(Aggregator.get_exprs(df)).rename(columns=Aggregator.get_cols_dictionary(df))
        
#         chunks.append(df)
        
#     df = pd.concat(chunks, axis=0) #pl.concat(chunks, how="vertical_relaxed")
#     df = df.drop_duplicates()
#     #df = df.unique(subset=["case_id"])
    
#     return df


    

# def feature_engineering(df_base, depth_0, depth_1, depth_2):
    
#     #add 2 new columns
#     df_base.loc[:, 'date_decision'] = pd.to_datetime(df_base.loc[:, 'date_decision'])
#     df_base.loc[:, 'month_decision'] = df_base.loc[:, 'date_decision'].dt.month
#     df_base.loc[:, 'day_decision'] = df_base.loc[:, 'date_decision'].dt.day
#     #df_base = (df_base.with_columns(month_decision = pl.col("date_decision").dt.month(), weekday_decision = pl.col("date_decision").dt.weekday(),))

    
#     #left join the DataFrame's in the list on 'case_id'
#     for i, df in enumerate(depth_0 + depth_1 + depth_2):
#         df_base = pd.merge(df_base, df, on='case_id', how='left', suffix=f"_{i}") #df_base = df_base.join(df, how="left", on="case_id", suffix=f"_{i}")
        
#     df_base = df_base.pipe(Pipeline.handle_dates)
    
#     return df_base




# TRAIN_DIR = "../data/raw/train/"

# data_store = {
#     "df_base": read_file(TRAIN_DIR + "train_base.csv"),
#     "depth_0": [
#         read_file(TRAIN_DIR + "train_static_cb_0.csv"),
#         read_files(TRAIN_DIR + "train_static_0_*.csv"),
#     ],
#     "depth_1": [
#         read_files(TRAIN_DIR + "train_applprev_1_*.csv", 1),
#         read_file(TRAIN_DIR + "train_tax_registry_a_1.csv", 1),
#         read_file(TRAIN_DIR + "train_tax_registry_b_1.csv", 1),
#         read_file(TRAIN_DIR + "train_tax_registry_c_1.csv", 1),
#         read_files(TRAIN_DIR + "train_credit_bureau_a_1_*.csv", 1),
#         read_file(TRAIN_DIR + "train_credit_bureau_b_1.csv", 1),
#         read_file(TRAIN_DIR + "train_other_1.csv", 1),
#         read_file(TRAIN_DIR + "train_person_1.csv", 1),
#         read_file(TRAIN_DIR + "train_deposit_1.csv", 1),
#         read_file(TRAIN_DIR + "train_debitcard_1.csv", 1),
#     ],
#     "depth_2": [
#         read_file(TRAIN_DIR + "train_credit_bureau_b_2.csv", 2),
#         read_files(TRAIN_DIR + "train_credit_bureau_a_2_*.csv", 2),
#     ]
# }

# #The *args will give you all positional arguments as a tuple
# #The **kwargs will give you all keyword arguments as a dictionary

# df_train = feature_engineering(**data_store)



# def preview_df(df):
#     """Of this DataFrame, prints the row and column count and then returns the concatenated first 5 and last % rows.

#     Args:
#         df (DataFrame): This pandas DataFrame object.
#     Returns:
#         df (DataFrame): The concatenated first 5 and last 5 rows of this pandas DataFrame.
#     """
#     if df.shape[0] > 9:
#         print(df.shape)
#         return pd.DataFrame(pd.concat([df.head(5), df.tail(5)]))
#     else:
#         return df

# preview_df(df_train)

time: 5.52 ms (started: 2024-04-06 22:21:08 -07:00)

## Rehauling Code 1: read_files()

In [11]:
# class Pipeline:
#     @staticmethod
#     def set_table_dtypes(df):
#         for col in df.columns:
#             if col in ["case_id", "WEEK_NUM", "num_group1", "num_group2"]:
#                 df.loc[:, col] = df.loc[:, col].astype('int32')
#             elif col in ["date_decision"]:
#                 df.loc[:, col] = pd.to_datetime(df.loc[:, col]) #.astype('datetime64[ns]') #with_columns(pl.col(col).cast(pl.Date))
#             elif col[-1] in ("P", "A"):
#                 df.loc[:, col] = df.loc[:, col].astype('float64') #with_columns(pl.col(col).cast(pl.Float64))
#             elif col[-1] in ("M",):
#                 df.loc[:, col] = df.loc[:, col].astype('object') #.astype('string') #with_columns(pl.col(col).cast(pl.String))
#             elif col[-1] in ("D",):
#                 df.loc[:, col] = pd.to_datetime(df.loc[:, col]) #.astype('datetime64[ns]') #with_columns(pl.col(col).cast(pl.Date))            

#         return df
    
#     @staticmethod
#     def handle_dates(df):
#         '''Edit date to number of days before the loan approval/refusal/denial decision date'''
#         for col in df.columns:
#             if col[-1] in ("D",):
#                 df.loc[:, col] = df.loc[:, col] - df.loc[:, 'date_decision'] #.with_columns(pl.col(col) - pl.col("date_decision"))
#                 df.loc[:, col] = df.loc[:, col].astype('timedelta64[D]') #df = df.with_columns(pl.col(col).dt.total_days())
#                 #with_columns(pl.col(col).cast(pl.Float32))
                
#         return df.drop("date_decision", "MONTH")

    
#     @staticmethod
#     def filter_cols(df):
#         for col in df.columns:
#             if col not in ["target", "case_id", "WEEK_NUM"]:
#                 isnull = df[col].isnull().mean()

#                 if isnull > 0.95:
#                     df = df.drop(columns=col)

#         for col in df.columns:
#             if (col not in ["target", "case_id", "WEEK_NUM"]) & (df[col].dtype == object):
#                 freq = df[col].nunique()

#                 if (freq == 1) | (freq > 200):
#                     df = df.drop(columns=col)

#         return df



# class Aggregator:
#     @staticmethod
#     def num_expr(df):
#         '''P is for Transform DPD (Days past due); A is for Transform amount'''
#         cols = [col for col in df.columns if col[-1] in ("P", "A")]

#         return {col:'max' for col in cols}
   

#     @staticmethod
#     def date_expr(df):
#         '''D is for Transform date'''
#         cols = [col for col in df.columns if col[-1] in ("D",)]

#         return {col:'max' for col in cols}

#     @staticmethod
#     def str_expr(df):
#         '''M is for  Masking categories'''
#         cols = [col for col in df.columns if col[-1] in ("M",)]
        
#         return {col:'max' for col in cols}

#     @staticmethod
#     def other_expr(df):
#         '''T is for Unspecified Transform; L is for Unspecified Transform'''
#         cols = [col for col in df.columns if col[-1] in ("T", "L")]
        
#         return {col:'max' for col in cols}

    
#     @staticmethod
#     def count_expr(df):
#         cols = [col for col in df.columns if "num_group" in col]

#         return {col:'max' for col in cols}
        

#     @staticmethod
#     def get_exprs(df):
#         return {**Aggregator.num_expr(df),
#                 #**Aggregator.date_expr(df), 
#                 #**Aggregator.str_expr(df), 
#                 #**Aggregator.other_expr(df),
#                 **Aggregator.count_expr(df)}

    
#     @staticmethod    
#     def get_cols_dictionary(df):
#         exprs = Aggregator.get_exprs(df)
#         cols = exprs.keys()
#         cols_dictionary = {f'{col}':f'{exprs[col]}_{col}' for col in cols}
#         print(f"cols_dictionary: {cols_dictionary}")
#         return cols_dictionary

    
# def read_files2(regex_path, depth=None):
#     chunks = []
#     for path in glob(str(regex_path)):
#         df = pd.read_csv(path)
#         df = df.pipe(Pipeline.set_table_dtypes)
        
#         if depth in [1, 2]:
#             df = df.groupby("case_id").agg(Aggregator.get_exprs(df)).rename(columns=Aggregator.get_cols_dictionary(df))

        
#         chunks.append(df)
        
#     df = pd.concat(chunks, axis=0)
#     return df.drop_duplicates()


# def preview_df(df):
#     """Of this DataFrame, prints the row and column count and then returns the concatenated first 5 and last % rows.

#     Args:
#         df (DataFrame): This pandas DataFrame object.
#     Returns:
#         df (DataFrame): The concatenated first 5 and last 5 rows of this pandas DataFrame.
#     """
#     if df.shape[0] > 9:
#         print(df.shape)
#         return pd.DataFrame(pd.concat([df.head(5), df.tail(5)]))
#     else:
#         return df

# TRAIN_DIR = "../data/raw/train/"
# #df = read_files2(TRAIN_DIR + "train_applprev_1_0.csv", 1)
# df = read_files2(TRAIN_DIR + "train_applprev_1_*.csv", 1)
# preview_df(df)

time: 2.11 ms (started: 2024-04-06 22:21:08 -07:00)

In [12]:
# TRAIN_DIR = "../data/raw/train/"
# df = read_files(TRAIN_DIR + "train_base.csv")
# #df = read_files2(TRAIN_DIR + "train_applprev_1_*.csv", 1)
# preview_df(df)

time: 449 µs (started: 2024-04-06 22:21:08 -07:00)

## Overhaul 2: to_datetime()

In [13]:
class Pipeline:
    @staticmethod
    def set_table_dtypes(df):
        for col in df.columns:
            if col in ["case_id", "WEEK_NUM", "num_group1", "num_group2"]:
                df.loc[:, col] = df.loc[:, col].astype('int32')
            elif col in ["date_decision"]:
                df.loc[:, col] = pd.to_datetime(df.loc[:, col]) #.astype('datetime64[ns]') #with_columns(pl.col(col).cast(pl.Date))
            elif col[-1] in ("P", "A"):
                df.loc[:, col] = df.loc[:, col].astype('float64') #with_columns(pl.col(col).cast(pl.Float64))
            elif col[-1] in ("M",):
                df.loc[:, col] = df.loc[:, col].astype('object') #.astype('string') #with_columns(pl.col(col).cast(pl.String))
            elif col[-1] in ("D",):
                df.loc[:, col] = pd.to_datetime(df.loc[:, col]) #.astype('datetime64[ns]') #with_columns(pl.col(col).cast(pl.Date))            

        return df
    
    @staticmethod
    def handle_dates(df):
        '''Edit date to number of days before the loan approval/refusal/denial decision date'''
        for col in df.columns:
            if col[-1] in ("D",):
                df.loc[:, col] = df.loc[:, col] - df.loc[:, 'date_decision'] #.with_columns(pl.col(col) - pl.col("date_decision"))
                df.loc[:, col] = df.loc[:, col].astype('timedelta64[D]') #df = df.with_columns(pl.col(col).dt.total_days())
                #with_columns(pl.col(col).cast(pl.Float32))
                
        return df.drop(columns=["date_decision", "MONTH"])

    
    @staticmethod
    def filter_cols(df):
        for col in df.columns:
            if col not in ["target", "case_id", "WEEK_NUM"]:
                isnull = df[col].isnull().mean()

                if isnull > 0.95:
                    df = df.drop(columns=col)

        for col in df.columns:
            if (col not in ["target", "case_id", "WEEK_NUM"]) & (df[col].dtype == object):
                freq = df[col].nunique()

                if (freq == 1) | (freq > 200):
                    df = df.drop(columns=col)

        return df



class Aggregator:
    @staticmethod
    def num_expr(df):
        '''P is for Transform DPD (Days past due); A is for Transform amount'''
        cols = [col for col in df.columns if col[-1] in ("P", "A")]

        return {col:'max' for col in cols}
   

    @staticmethod
    def date_expr(df):
        '''D is for Transform date'''
        cols = [col for col in df.columns if col[-1] in ("D",)]

        return {col:'max' for col in cols}

    @staticmethod
    def str_expr(df):
        '''M is for  Masking categories'''
        cols = [col for col in df.columns if col[-1] in ("M",)]
        
        return {col:'max' for col in cols}

    @staticmethod
    def other_expr(df):
        '''T is for Unspecified Transform; L is for Unspecified Transform'''
        cols = [col for col in df.columns if col[-1] in ("T", "L")]
        
        return {col:'max' for col in cols}

    
    @staticmethod
    def count_expr(df):
        cols = [col for col in df.columns if "num_group" in col]

        return {col:'max' for col in cols}
        

    @staticmethod
    def get_exprs(df):
        return {**Aggregator.num_expr(df),
                #**Aggregator.date_expr(df), 
                #**Aggregator.str_expr(df), 
                #**Aggregator.other_expr(df),
                **Aggregator.count_expr(df)}

    
    @staticmethod    
    def get_cols_dictionary(df):
        exprs = Aggregator.get_exprs(df)
        cols = exprs.keys()
        cols_dictionary = {f'{col}':f'{exprs[col]}_{col}' for col in cols}
        print(f"cols_dictionary: {cols_dictionary}")
        return cols_dictionary

    
    

def read_file(path, depth=None):
    '''read in the file; the data type by column name or suffix'''
    df = pd.read_csv(path)
    df = df.pipe(Pipeline.set_table_dtypes)
    
    if depth in [1, 2]:
        df = df.groupby("case_id").agg(Aggregator.get_exprs(df)).rename(columns=Aggregator.get_cols_dictionary(df)) #df = df.groupby("case_id").agg(Aggregator.get_exprs(df))
    
    return df


def read_files(regex_path, depth=None):
    chunks = []
    for path in glob(str(regex_path)):
        df = pd.read_csv(path)
        df = df.pipe(Pipeline.set_table_dtypes)
        
        if depth in [1, 2]:
            df = df.groupby("case_id").agg(Aggregator.get_exprs(df)).rename(columns=Aggregator.get_cols_dictionary(df))

        
        chunks.append(df)
        
    df = pd.concat(chunks, axis=0)
    return df.drop_duplicates()





def feature_engineering(df_base, depth_0, depth_1, depth_2):
    
    #add 2 new columns
    df_base.loc[:, 'date_decision'] = pd.to_datetime(df_base.loc[:, 'date_decision'])
    df_base.loc[:, 'month_decision'] = df_base.loc[:, 'date_decision'].dt.month
    df_base.loc[:, 'day_decision'] = df_base.loc[:, 'date_decision'].dt.day
    #df_base = (df_base.with_columns(month_decision = pl.col("date_decision").dt.month(), weekday_decision = pl.col("date_decision").dt.weekday(),))

    
    #left join the DataFrame's in the list on 'case_id'
    for i, df in enumerate(depth_0 + depth_1 + depth_2):
        df_base = pd.merge(df_base, df, on='case_id', how='left', suffixes=("", f"_{i}")) #df_base = df_base.join(df, how="left", on="case_id", suffix=f"_{i}")
        
    df_base = df_base.pipe(Pipeline.handle_dates)
    
    return df_base




TRAIN_DIR = "../data/raw/train/"

data_store = {
    "df_base": read_file(TRAIN_DIR + "train_base.csv"),
    "depth_0": [
        read_file(TRAIN_DIR + "train_static_cb_0.csv"),
        read_files(TRAIN_DIR + "train_static_0_*.csv"),
    ],
    "depth_1": [
        read_files(TRAIN_DIR + "train_applprev_1_*.csv", 1),
        read_file(TRAIN_DIR + "train_tax_registry_a_1.csv", 1),
        read_file(TRAIN_DIR + "train_tax_registry_b_1.csv", 1),
        read_file(TRAIN_DIR + "train_tax_registry_c_1.csv", 1),
        read_files(TRAIN_DIR + "train_credit_bureau_a_1_*.csv", 1),
        read_file(TRAIN_DIR + "train_credit_bureau_b_1.csv", 1),
        read_file(TRAIN_DIR + "train_other_1.csv", 1),
        read_file(TRAIN_DIR + "train_person_1.csv", 1),
        read_file(TRAIN_DIR + "train_deposit_1.csv", 1),
        read_file(TRAIN_DIR + "train_debitcard_1.csv", 1),
    ],
    "depth_2": [
        read_file(TRAIN_DIR + "train_credit_bureau_b_2.csv", 2),
        read_files(TRAIN_DIR + "train_credit_bureau_a_2_*.csv", 2),
    ]
}



def preview_df(df):
    """Of this DataFrame, prints the row and column count and then returns the concatenated first 5 and last % rows.

    Args:
        df (DataFrame): This pandas DataFrame object.
    Returns:
        df (DataFrame): The concatenated first 5 and last 5 rows of this pandas DataFrame.
    """
    if df.shape[0] > 9:
        print(df.shape)
        return pd.DataFrame(pd.concat([df.head(5), df.tail(5)]))
    else:
        return df

    
#The *args will give you all positional arguments as a tuple
#The **kwargs will give you all keyword arguments as a dictionary

df_train = feature_engineering(**data_store)



preview_df(df_train)

/var/folders/77/y4hv4_s9751293nzv4yrfrtm0000gn/T/ipykernel_4499/2038672215.py:110: DtypeWarning: Columns (1,2,3,4,7,45,46,47,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/77/y4hv4_s9751293nzv4yrfrtm0000gn/T/ipykernel_4499/2038672215.py:122: DtypeWarning: Columns (20,45,46,56,57,84,143,146,167) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/77/y4hv4_s9751293nzv4yrfrtm0000gn/T/ipykernel_4499/2038672215.py:122: DtypeWarning: Columns (20,45,46,53,57,84,143,146,167) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/77/y4hv4_s9751293nzv4yrfrtm0000gn/T/ipykernel_4499/2038672215.py:122: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

cols_dictionary: {'actualdpd_943P': 'max_actualdpd_943P', 'annuity_853A': 'max_annuity_853A', 'credacc_actualbalance_314A': 'max_credacc_actualbalance_314A', 'credacc_credlmt_575A': 'max_credacc_credlmt_575A', 'credacc_maxhisbal_375A': 'max_credacc_maxhisbal_375A', 'credacc_minhisbal_90A': 'max_credacc_minhisbal_90A', 'credamount_590A': 'max_credamount_590A', 'currdebt_94A': 'max_currdebt_94A', 'downpmt_134A': 'max_downpmt_134A', 'mainoccupationinc_437A': 'max_mainoccupationinc_437A', 'maxdpdtolerance_577P': 'max_maxdpdtolerance_577P', 'outstandingdebt_522A': 'max_outstandingdebt_522A', 'revolvingaccount_394A': 'max_revolvingaccount_394A', 'num_group1': 'max_num_group1'}

/var/folders/77/y4hv4_s9751293nzv4yrfrtm0000gn/T/ipykernel_4499/2038672215.py:122: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

cols_dictionary: {'actualdpd_943P': 'max_actualdpd_943P', 'annuity_853A': 'max_annuity_853A', 'credacc_actualbalance_314A': 'max_credacc_actualbalance_314A', 'credacc_credlmt_575A': 'max_credacc_credlmt_575A', 'credacc_maxhisbal_375A': 'max_credacc_maxhisbal_375A', 'credacc_minhisbal_90A': 'max_credacc_minhisbal_90A', 'credamount_590A': 'max_credamount_590A', 'currdebt_94A': 'max_currdebt_94A', 'downpmt_134A': 'max_downpmt_134A', 'mainoccupationinc_437A': 'max_mainoccupationinc_437A', 'maxdpdtolerance_577P': 'max_maxdpdtolerance_577P', 'outstandingdebt_522A': 'max_outstandingdebt_522A', 'revolvingaccount_394A': 'max_revolvingaccount_394A', 'num_group1': 'max_num_group1'}
cols_dictionary: {'amount_4527230A': 'max_amount_4527230A', 'num_group1': 'max_num_group1'}
cols_dictionary: {'amount_4917619A': 'max_amount_4917619A', 'num_group1': 'max_num_group1'}
cols_dictionary: {'pmtamount_36A': 'max_pmtamount_36A', 'num_group1': 'max_num_group1'}
cols_dictionary: {'credlmt_230A': 'max_credlmt_230A', 'credlmt_935A': 'max_credlmt_935A', 'debtoutstand_525A': 'max_debtoutstand_525A', 'debtoverdue_47A': 'max_debtoverdue_47A', 'dpdmax_139P': 'max_dpdmax_139P', 'dpdmax_757P': 'max_dpdmax_757P', 'instlamount_768A': 'max_instlamount_768A', 'instlamount_852A': 'max_instlamount_852A', 'monthlyinstlamount_332A': 'max_monthlyinstlamount_332A', 'monthlyinstlamount_674A': 'max_monthlyinstlamount_674A', 'outstandingamount_354A': 'max_outstandingamount_354A', 'outstandingamount_362A': 'max_outstandingamount_362A', 'overdueamount_31A': 'max_overdueamount_31A', 'overdueamount_659A': 'max_overdueamount_659A', 'overdueamountmax2_14A': 'max_overdueamountmax2_14A', 'overdueamountmax2_398A': 'max_overdueamountmax2_398A', 'overdueamountmax_155A': 'max_overdueamountmax_155A', 'overdueamountmax_35A': 'max_overdueamountmax_35A', 'residualamount_488A': 'max_residualamount_488A', 'residualamount_856A': 'max_residualamount_856A', 'totalamount_6A': 'max_totalamount_6A', 'totalamount_996A': 'max_totalamount_996A', 'totaldebtoverduevalue_178A': 'max_totaldebtoverduevalue_178A', 'totaldebtoverduevalue_718A': 'max_totaldebtoverduevalue_718A', 'totaloutstanddebtvalue_39A': 'max_totaloutstanddebtvalue_39A', 'totaloutstanddebtvalue_668A': 'max_totaloutstanddebtvalue_668A', 'num_group1': 'max_num_group1'}
cols_dictionary: {'credlmt_230A': 'max_credlmt_230A', 'credlmt_935A': 'max_credlmt_935A', 'debtoutstand_525A': 'max_debtoutstand_525A', 'debtoverdue_47A': 'max_debtoverdue_47A', 'dpdmax_139P': 'max_dpdmax_139P', 'dpdmax_757P': 'max_dpdmax_757P', 'instlamount_768A': 'max_instlamount_768A', 'instlamount_852A': 'max_instlamount_852A', 'monthlyinstlamount_332A': 'max_monthlyinstlamount_332A', 'monthlyinstlamount_674A': 'max_monthlyinstlamount_674A', 'outstandingamount_354A': 'max_outstandingamount_354A', 'outstandingamount_362A': 'max_outstandingamount_362A', 'overdueamount_31A': 'max_overdueamount_31A', 'overdueamount_659A': 'max_overdueamount_659A', 'overdueamountmax2_14A': 'max_overdueamountmax2_14A', 'overdueamountmax2_398A': 'max_overdueamountmax2_398A', 'overdueamountmax_155A': 'max_overdueamountmax_155A', 'overdueamountmax_35A': 'max_overdueamountmax_35A', 'residualamount_488A': 'max_residualamount_488A', 'residualamount_856A': 'max_residualamount_856A', 'totalamount_6A': 'max_totalamount_6A', 'totalamount_996A': 'max_totalamount_996A', 'totaldebtoverduevalue_178A': 'max_totaldebtoverduevalue_178A', 'totaldebtoverduevalue_718A': 'max_totaldebtoverduevalue_718A', 'totaloutstanddebtvalue_39A': 'max_totaloutstanddebtvalue_39A', 'totaloutstanddebtvalue_668A': 'max_totaloutstanddebtvalue_668A', 'num_group1': 'max_num_group1'}

/var/folders/77/y4hv4_s9751293nzv4yrfrtm0000gn/T/ipykernel_4499/2038672215.py:122: DtypeWarning: Columns (11,12,14,30,44,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

cols_dictionary: {'credlmt_230A': 'max_credlmt_230A', 'credlmt_935A': 'max_credlmt_935A', 'debtoutstand_525A': 'max_debtoutstand_525A', 'debtoverdue_47A': 'max_debtoverdue_47A', 'dpdmax_139P': 'max_dpdmax_139P', 'dpdmax_757P': 'max_dpdmax_757P', 'instlamount_768A': 'max_instlamount_768A', 'instlamount_852A': 'max_instlamount_852A', 'monthlyinstlamount_332A': 'max_monthlyinstlamount_332A', 'monthlyinstlamount_674A': 'max_monthlyinstlamount_674A', 'outstandingamount_354A': 'max_outstandingamount_354A', 'outstandingamount_362A': 'max_outstandingamount_362A', 'overdueamount_31A': 'max_overdueamount_31A', 'overdueamount_659A': 'max_overdueamount_659A', 'overdueamountmax2_14A': 'max_overdueamountmax2_14A', 'overdueamountmax2_398A': 'max_overdueamountmax2_398A', 'overdueamountmax_155A': 'max_overdueamountmax_155A', 'overdueamountmax_35A': 'max_overdueamountmax_35A', 'residualamount_488A': 'max_residualamount_488A', 'residualamount_856A': 'max_residualamount_856A', 'totalamount_6A': 'max_totalamount_6A', 'totalamount_996A': 'max_totalamount_996A', 'totaldebtoverduevalue_178A': 'max_totaldebtoverduevalue_178A', 'totaldebtoverduevalue_718A': 'max_totaldebtoverduevalue_718A', 'totaloutstanddebtvalue_39A': 'max_totaloutstanddebtvalue_39A', 'totaloutstanddebtvalue_668A': 'max_totaloutstanddebtvalue_668A', 'num_group1': 'max_num_group1'}
cols_dictionary: {'credlmt_230A': 'max_credlmt_230A', 'credlmt_935A': 'max_credlmt_935A', 'debtoutstand_525A': 'max_debtoutstand_525A', 'debtoverdue_47A': 'max_debtoverdue_47A', 'dpdmax_139P': 'max_dpdmax_139P', 'dpdmax_757P': 'max_dpdmax_757P', 'instlamount_768A': 'max_instlamount_768A', 'instlamount_852A': 'max_instlamount_852A', 'monthlyinstlamount_332A': 'max_monthlyinstlamount_332A', 'monthlyinstlamount_674A': 'max_monthlyinstlamount_674A', 'outstandingamount_354A': 'max_outstandingamount_354A', 'outstandingamount_362A': 'max_outstandingamount_362A', 'overdueamount_31A': 'max_overdueamount_31A', 'overdueamount_659A': 'max_overdueamount_659A', 'overdueamountmax2_14A': 'max_overdueamountmax2_14A', 'overdueamountmax2_398A': 'max_overdueamountmax2_398A', 'overdueamountmax_155A': 'max_overdueamountmax_155A', 'overdueamountmax_35A': 'max_overdueamountmax_35A', 'residualamount_488A': 'max_residualamount_488A', 'residualamount_856A': 'max_residualamount_856A', 'totalamount_6A': 'max_totalamount_6A', 'totalamount_996A': 'max_totalamount_996A', 'totaldebtoverduevalue_178A': 'max_totaldebtoverduevalue_178A', 'totaldebtoverduevalue_718A': 'max_totaldebtoverduevalue_718A', 'totaloutstanddebtvalue_39A': 'max_totaloutstanddebtvalue_39A', 'totaloutstanddebtvalue_668A': 'max_totaloutstanddebtvalue_668A', 'num_group1': 'max_num_group1'}

/var/folders/77/y4hv4_s9751293nzv4yrfrtm0000gn/T/ipykernel_4499/2038672215.py:110: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

cols_dictionary: {'amount_1115A': 'max_amount_1115A', 'credlmt_1052A': 'max_credlmt_1052A', 'credlmt_228A': 'max_credlmt_228A', 'credlmt_3940954A': 'max_credlmt_3940954A', 'debtpastduevalue_732A': 'max_debtpastduevalue_732A', 'debtvalue_227A': 'max_debtvalue_227A', 'dpd_550P': 'max_dpd_550P', 'dpd_733P': 'max_dpd_733P', 'dpdmax_851P': 'max_dpdmax_851P', 'installmentamount_644A': 'max_installmentamount_644A', 'installmentamount_833A': 'max_installmentamount_833A', 'instlamount_892A': 'max_instlamount_892A', 'maxdebtpduevalodued_3940955A': 'max_maxdebtpduevalodued_3940955A', 'overdueamountmax_950A': 'max_overdueamountmax_950A', 'pmtdaysoverdue_1135P': 'max_pmtdaysoverdue_1135P', 'residualamount_1093A': 'max_residualamount_1093A', 'residualamount_127A': 'max_residualamount_127A', 'residualamount_3940956A': 'max_residualamount_3940956A', 'totalamount_503A': 'max_totalamount_503A', 'totalamount_881A': 'max_totalamount_881A', 'num_group1': 'max_num_group1'}
cols_dictionary: {'amtdebitincoming_4809443A': 'max_amtdebitincoming_4809443A', 'amtdebitoutgoing_4809440A': 'max_amtdebitoutgoing_4809440A', 'amtdepositbalance_4809441A': 'max_amtdepositbalance_4809441A', 'amtdepositincoming_4809444A': 'max_amtdepositincoming_4809444A', 'amtdepositoutgoing_4809442A': 'max_amtdepositoutgoing_4809442A', 'num_group1': 'max_num_group1'}

/var/folders/77/y4hv4_s9751293nzv4yrfrtm0000gn/T/ipykernel_4499/2038672215.py:110: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

cols_dictionary: {'mainoccupationinc_384A': 'max_mainoccupationinc_384A', 'num_group1': 'max_num_group1'}
cols_dictionary: {'amount_416A': 'max_amount_416A', 'num_group1': 'max_num_group1'}
cols_dictionary: {'last180dayaveragebalance_704A': 'max_last180dayaveragebalance_704A', 'last180dayturnover_1134A': 'max_last180dayturnover_1134A', 'last30dayturnover_651A': 'max_last30dayturnover_651A', 'num_group1': 'max_num_group1'}
cols_dictionary: {'pmts_dpdvalue_108P': 'max_pmts_dpdvalue_108P', 'pmts_pmtsoverdue_635A': 'max_pmts_pmtsoverdue_635A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
cols_dictionary: {'pmts_dpd_1073P': 'max_pmts_dpd_1073P', 'pmts_dpd_303P': 'max_pmts_dpd_303P', 'pmts_overdue_1140A': 'max_pmts_overdue_1140A', 'pmts_overdue_1152A': 'max_pmts_overdue_1152A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
cols_dictionary: {'pmts_dpd_1073P': 'max_pmts_dpd_1073P', 'pmts_dpd_303P': 'max_pmts_dpd_303P', 'pmts_overdue_1140A': 'max_pmts_overdue_1140A', 'pmts_overdue_1152A': 'max_pmts_overdue_1152A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
cols_dictionary: {'pmts_dpd_1073P': 'max_pmts_dpd_1073P', 'pmts_dpd_303P': 'max_pmts_dpd_303P', 'pmts_overdue_1140A': 'max_pmts_overdue_1140A', 'pmts_overdue_1152A': 'max_pmts_overdue_1152A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
cols_dictionary: {'pmts_dpd_1073P': 'max_pmts_dpd_1073P', 'pmts_dpd_303P': 'max_pmts_dpd_303P', 'pmts_overdue_1140A': 'max_pmts_overdue_1140A', 'pmts_overdue_1152A': 'max_pmts_overdue_1152A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
cols_dictionary: {'pmts_dpd_1073P': 'max_pmts_dpd_1073P', 'pmts_dpd_303P': 'max_pmts_dpd_303P', 'pmts_overdue_1140A': 'max_pmts_overdue_1140A', 'pmts_overdue_1152A': 'max_pmts_overdue_1152A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
cols_dictionary: {'pmts_dpd_1073P': 'max_pmts_dpd_1073P', 'pmts_dpd_303P': 'max_pmts_dpd_303P', 'pmts_overdue_1140A': 'max_pmts_overdue_1140A', 'pmts_overdue_1152A': 'max_pmts_overdue_1152A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
cols_dictionary: {'pmts_dpd_1073P': 'max_pmts_dpd_1073P', 'pmts_dpd_303P': 'max_pmts_dpd_303P', 'pmts_overdue_1140A': 'max_pmts_overdue_1140A', 'pmts_overdue_1152A': 'max_pmts_overdue_1152A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
cols_dictionary: {'pmts_dpd_1073P': 'max_pmts_dpd_1073P', 'pmts_dpd_303P': 'max_pmts_dpd_303P', 'pmts_overdue_1140A': 'max_pmts_overdue_1140A', 'pmts_overdue_1152A': 'max_pmts_overdue_1152A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
cols_dictionary: {'pmts_dpd_1073P': 'max_pmts_dpd_1073P', 'pmts_dpd_303P': 'max_pmts_dpd_303P', 'pmts_overdue_1140A': 'max_pmts_overdue_1140A', 'pmts_overdue_1152A': 'max_pmts_overdue_1152A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
cols_dictionary: {'pmts_dpd_1073P': 'max_pmts_dpd_1073P', 'pmts_dpd_303P': 'max_pmts_dpd_303P', 'pmts_overdue_1140A': 'max_pmts_overdue_1140A', 'pmts_overdue_1152A': 'max_pmts_overdue_1152A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
cols_dictionary: {'pmts_dpd_1073P': 'max_pmts_dpd_1073P', 'pmts_dpd_303P': 'max_pmts_dpd_303P', 'pmts_overdue_1140A': 'max_pmts_overdue_1140A', 'pmts_overdue_1152A': 'max_pmts_overdue_1152A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
(1526659, 316)

,case_id,WEEK_NUM,target,month_decision,day_decision,assignmentdate_238D,assignmentdate_4527235D,assignmentdate_4955616D,birthdate_574D,contractssum_5085716L,dateofbirth_337D,dateofbirth_342D,days120_123L,days180_256L,days30_165L,days360_512L,days90_310L,description_5085714M,education_1103M,education_88M,firstquarter_103L,for3years_128L,for3years_504L,for3years_584L,formonth_118L,formonth_206L,formonth_535L,forquarter_1017L,forquarter_462L,forquarter_634L,fortoday_1092L,forweek_1077L,forweek_528L,forweek_601L,foryear_618L,foryear_818L,foryear_850L,fourthquarter_440L,maritalst_385M,maritalst_893M,numberofqueries_373L,pmtaverage_3A,pmtaverage_4527227A,pmtaverage_4955615A,pmtcount_4527229L,pmtcount_4955617L,pmtcount_693L,pmtscount_423L,pmtssum_45A,requesttype_4525192L,responsedate_1012D,responsedate_4527233D,responsedate_4917613D,riskassesment_302T,riskassesment_940T,secondquarter_766L,thirdquarter_1082L,actualdpdtolerance_344P,amtinstpaidbefduel24m_4187115A,annuity_780A,annuitynextmonth_57A,applicationcnt_361L,applications30d_658L,applicationscnt_1086L,applicationscnt_464L,applicationscnt_629L,applicationscnt_867L,avgdbddpdlast24m_3658932P,avgdbddpdlast3m_4187120P,avgdbdtollast24m_4525197P,avgdpdtolclosure24_3658938P,avginstallast24m_3658937A,avglnamtstart24m_4525187A,avgmaxdpdlast9m_3716943P,avgoutstandbalancel6m_4187114A,avgpmtlast12m_4525200A,bankacctype_710L,cardtype_51L,clientscnt12m_3712952L,clientscnt3m_3712950L,clientscnt6m_3712949L,clientscnt_100L,clientscnt_1022L,clientscnt_1071L,clientscnt_1130L,clientscnt_136L,clientscnt_157L,clientscnt_257L,clientscnt_304L,clientscnt_360L,clientscnt_493L,clientscnt_533L,clientscnt_887L,clientscnt_946L,cntincpaycont9m_3716944L,cntpmts24_3658933L,commnoinclast6m_3546845L,credamount_770A,credtype_322L,currdebt_22A,currdebtcredtyperange_828A,datefirstoffer_1144D,datelastinstal40dpd_247D,datelastunpaid_3546854D,daysoverduetolerancedd_3976961L,deferredmnthsnum_166L,disbursedcredamount_1113A,disbursementtype_67L,downpmt_116A,dtlastpmtallstes_4499206D,eir_270L,equalitydataagreement_891L,equalityempfrom_62L,firstclxcampaign_1125D,firstdatedue_489D,homephncnt_628L,inittransactionamount_650A,inittransactioncode_186L,interestrate_311L,interestrategrace_34L,isbidproduct_1095L,isbidproductrequest_292L,isdebitcard_729L,lastactivateddate_801D,lastapplicationdate_877D,lastapprcommoditycat_1041M,lastapprcommoditytypec_5251766M,lastapprcredamount_781A,lastapprdate_640D,lastcancelreason_561M,lastdelinqdate_224D,lastdependentsnum_448L,lastotherinc_902A,lastotherlnsexpense_631A,lastrejectcommoditycat_161M,lastrejectcommodtypec_5251769M,lastrejectcredamount_222A,lastrejectdate_50D,lastrejectreason_759M,lastrejectreasonclient_4145040M,lastrepayingdate_696D,lastst_736L,maininc_215A,mastercontrelectronic_519L,mastercontrexist_109L,maxannuity_159A,maxannuity_4075009A,maxdbddpdlast1m_3658939P,maxdbddpdtollast12m_3658940P,maxdbddpdtollast6m_4187119P,maxdebt4_972A,maxdpdfrom6mto36m_3546853P,maxdpdinstldate_3546855D,maxdpdinstlnum_3546846P,maxdpdlast12m_727P,maxdpdlast24m_143P,maxdpdlast3m_392P,maxdpdlast6m_474P,maxdpdlast9m_1059P,maxdpdtolerance_374P,maxinstallast24m_3658928A,maxlnamtstart6m_4525199A,maxoutstandbalancel12m_4187113A,maxpmtlast3m_4525190A,mindbddpdlast24m_3658935P,mindbdtollast24m_4525191P,mobilephncnt_593L,monthsannuity_845L,numactivecreds_622L,numactivecredschannel_414L,numactiverelcontr_750L,numcontrs3months_479L,numincomingpmts_3546848L,numinstlallpaidearly3d_817L,numinstls_657L,numinstlsallpaid_934L,numinstlswithdpd10_728L,numinstlswithdpd5_4187116L,numinstlswithoutdpd_562L,numinstmatpaidtearly2d_4499204L,numinstpaid_4499208L,numinstpaidearly3d_3546850L,numinstpaidearly3dest_4493216L,numinstpaidearly5d_1087L,numinstpaidearly5dest_4493211L,numinstpaidearly5dobd_4499205L,numinstpaidearly_338L,numinstpaidearlyest_4493214L,numinstpaidlastcontr_4325080L,numinstpaidlate1d_3546852L,numinstregularpaid_973L,numinstregularpaidest_4493210L,numinsttopaygr_769L,numinsttopaygrest_4493213L,numinstunpaidmax_3546851L,numinstunpaidmaxest_4493212L,numnotactivated_1143L,numpmtchanneldd_318L,numrejects9m_859L,opencred_647L,paytype1st_925L,paytype_783L,payvacationpostpone_4187118D,pctinstlsallpaidearl3d_427L,pctinstlsallpaidlat10d_839L,pctinstlsallpaidlate1d_3546856L,pctinstlsallpaidlate4d_3546849L,pctinstlsallpaidlate6d_3546844L,pmtnum_254L,posfpd10lastmonth_333P,posfpd30lastmonth_3976960P,posfstqpd30lastmonth_3976962P,previouscontdistrict_112M,price_1097A,sellerplacecnt_915L,sellerplacescnt_216L,sumoutstandtotal_3546847A,sumoutstandtotalest_4493215A,totaldebt_9A,totalsettled_863A,totinstallast1m_4525188A,twobodfilling_608L,typesuite_864L,validfrom_1069D,max_actualdpd_943P,max_annuity_853A,max_credacc_actualbalance_314A,max_credacc_credlmt_575A,max_credacc_maxhisbal_375A,max_credacc_minhisbal_90A,max_credamount_590A,max_currdebt_94A,max_downpmt_134A,max_mainoccupationinc_437A,max_maxdpdtolerance_577P,max_outstandingdebt_522A,max_revolvingaccount_394A,max_num_group1,max_amount_4527230A,max_num_group1_3,max_amount_4917619A,max_num_group1_4,max_pmtamount_36A,max_num_group1_5,max_credlmt_230A,max_credlmt_935A,max_debtoutstand_525A,max_debtoverdue_47A,max_dpdmax_139P,max_dpdmax_757P,max_instlamount_768A,max_instlamount_852A,max_monthlyinstlamount_332A,max_monthlyinstlamount_674A,max_outstandingamount_354A,max_outstandingamount_362A,max_overdueamount_31A,max_overdueamount_659A,max_overdueamountmax2_14A,max_overdueamountmax2_398A,max_overdueamountmax_155A,max_overdueamountmax_35A,max_residualamount_488A,max_residualamount_856A,max_totalamount_6A,max_totalamount_996A,max_totaldebtoverduevalue_178A,max_totaldebtoverduevalue_718A,max_totaloutstanddebtvalue_39A,max_totaloutstanddebtvalue_668A,max_num_group1_6,max_amount_1115A,max_credlmt_1052A,max_credlmt_228A,max_credlmt_3940954A,max_debtpastduevalue_732A,max_debtvalue_227A,max_dpd_550P,max_dpd_733P,max_dpdmax_851P,max_installmentamount_644A,max_installmentamount_833A,max_instlamount_892A,max_maxdebtpduevalodued_3940955A,max_overdueamountmax_950A,max_pmtdaysoverdue_1135P,max_residualamount_1093A,max_residualamount_127A,max_residualamount_3940956A,max_totalamount_503A,max_totalamount_881A,max_num_group1_7,max_amtdebitincoming_4809443A,max_amtdebitoutgoing_4809440A,max_amtdepositbalance_4809441A,max_amtdepositincoming_4809444A,max_amtdepositoutgoing_4809442A,max_num_group1_8,max_mainoccupationinc_384A,max_num_group1_9,max_amount_416A,max_num_group1_10,max_last180dayaveragebalance_704A,max_last180dayturnover_1134A,max_last30dayturnover_651A,max_num_group1_11,max_pmts_dpdvalue_108P,max_pmts_pmtsoverdue_635A,max_num_group1_12,max_num_group2,max_pmts_dpd_1073P,max_pmts_dpd_303P,max_pmts_overdue_1140A,max_pmts_overdue_1152A,max_num_group1_13,max_num_group2_13
0,0,0,0,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1917.6000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,30000.0,CAL,0.0,0.0,NaN,NaN,NaN,NaN,0.0,30000.000,GBA,0.0,NaN,0.4500,NaN,NaN,NaN,NaN,0.0,NaN,CASH,0.4500,NaN,False,NaN,NaN,NaN,NaN,a55475b1,a55475b1,NaN,NaN,a55475b1,NaN,NaN,NaN,NaN,a55475b1,a55475b1,NaN,NaN,a55475b1,a55475b1,NaN,NaN,NaN,0.0,0.0,0.000,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,OTHER,OTHER,NaN,NaN,NaN,NaN,NaN,NaN,24.0,0.0,0.0,NaN,a55475b1,NaN,0.0,0.0,NaN,NaN,0.0,0.00,NaN,BO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10800.0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0,0,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3134.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,19999.8,CAL,0.0,0.0,NaN,NaN,NaN,NaN,0.0,19999.800,GBA,0.0,NaN,0.2999,NaN,NaN,NaN,NaN,0.0,NaN,CASH,0.2999,0.0,False,NaN,NaN,NaN,NaN,a55475b1,a55475b1,NaN,NaN,a55475b1,NaN,NaN,NaN,NaN,a55475b1,a55475b1,NaN,NaN,a55475b1,a55475b1,NaN,NaN,NaN,0.0,0.0,0.000,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,OTHER,OTHER,NaN,NaN,NaN,NaN,NaN,NaN,18.0,0.0,0.0,NaN,a55475b1,NaN,0.0,0.0,NaN,NaN,0.0,0.00,NaN,BO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10000.0,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,0,0,1,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4937.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,78000.0,CAL,0.0,0.0,NaN,NaN,NaN,NaN,0.0,78000.000,GBA,0.0,NaN,0.4500,NaN,NaN,NaN,NaN,1.0,NaN,CASH,0.4500,NaN,False,NaN,NaN,NaN,-2102.0,a55475b1,a55475b1,NaN,NaN,a55475b1,NaN,NaN,NaN,NaN,a55475b1,a55475b1,10000.0,-2102.0,a55475b1,a55475b1,NaN,D,NaN,0.0,0.0,0.000,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,False,OTHER,OTHER,NaN,NaN,NaN,NaN,NaN,NaN,36.0,0.0,0.0,NaN,a55475b1,NaN,0.0,0.0,NaN,NaN,0.0,0.00,NaN,BO,AL,NaN,0.0,1682.4,NaN,0.0,NaN,NaN,16000.0,NaN,0.0,8200.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14000.0,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,0,0,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4643.6000,0.0,0.0,1.0,0.0,2.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,40000.0,CAL,0.0,0.0,NaN,NaN,NaN,NaN,0.0,40000.000,GBA,0.0,NaN,0.4200,True,True,NaN,NaN,0.0,NaN,CASH,0.4200,0.0,False,NaN,NaN,NaN,4.0,a55475b1,a55475b1,NaN,NaN,P94_109_143,NaN,NaN,NaN,NaN,a55475b1,a55475b1,59999.8,4.0,P94_109_143,a55475b1,NaN,D,NaN,0.0,0.0,0.000,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.0,0.0,0.0,1.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,False,OTHER,OTHER,NaN,NaN,NaN,NaN,NaN,NaN,12.0,0.0,0.0,NaN,a55475b1,NaN,1.0,1.0,NaN,NaN,0.0,0.00,NaN,BO,AL,NaN,0.0,6140.0,NaN,0.0,NaN,NaN,59999.8,NaN,0.0,11000.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10000.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,0,1,1,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3390.2000,0.0,0.0,1.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,44000.0,CAL,0.0,0.0,NaN,NaN,NaN,NaN,0.0,44000.000,GBA,0.0,NaN,0.4500,NaN,NaN,NaN,NaN,1.0,NaN,CASH,0.4500,NaN,False,NaN,NaN,NaN,4.0,a55475b1,a55475b1,NaN,NaN,P24_27_36,NaN,NaN,NaN,NaN,a55475b1,a55475b1,NaN,NaN,a55475b1,a55475b1,NaN,T,NaN,0.0,0.0,0.000,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,False,OTHER,OTHER,NaN,NaN,NaN,NaN,NaN,NaN,24.0,0.0,0.0,NaN,a55475b1,NaN,0.0,0.0,NaN,NaN,0.0,0.00,NaN,BO,AL,NaN,0.0,2556.6,NaN,0.0,NaN,NaN,40000.0,NaN,0.0,16000.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24000.0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1526654,2703450,91,0,10,5,NaN,NaN,-998.0,NaN,52863.59,-22193.0,NaN,0.0,0.0,0.0,0.0,0.0,2fc785b2,a55475b1,a55475b1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,a55475b1,a55475b1,0.0,NaN,NaN,12155.0,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,NaN,1.0,1.0,0.0,176561.36,3675.4001,0.0,0.0,0.0,0.0,0.0,0.0,10.0,-23.0,-43.0,-23.0,0.0,7356.8003,NaN,0.0,16392.496,6750.2,CA,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,24.0,0.0,30000.0,CAL,0.0,0.0,-2785.0,NaN,-1481.0,8.0,0.0,30000.000,GBA,0.0,NaN,0.4200,NaN,NaN,-1610.0,-4833.0,0.0,NaN,CASH,0.4200,NaN,True,NaN,NaN,-355.0,-362.0,P12_6_178,P142_50_170,20020.0,-362.0,a55475b1,-1481.0,NaN,NaN,NaN,a55475b1,a55475b1,150000.0,-1040.0,P94_109_143,P94_109_143,NaN,K,36000.0,0.0,0.0,75521.910,NaN,0.0,0.0,0.0,105019.79,0.0,-1512.0,6.0,0.0,0.0,0.0,0.0,0.0,8.0,46718.2000,49651.402,77533.760,14346.319,-144.0,-144.0,3.0,65.0,1.0,0.0,1.0,0.0,92.0,106.0,0.0,112.0,0.0,1.0,117.0,106.0,113.0,103.0,103.0,11.0,11.0,99.0,99.0,99.0,12.0,4.0,113.0,113.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,OTHER,OTHER,NaN,0.91150,0.02655,0.03540,0.03540,0.0354,12.0,0.0,0.0,0.0,P123_39_170,0.0,0.0,8.0,0.0,0.0,0.0,428159.66,14346.319,FO,NaN,NaN,0.0,30875.0,0.092,0.0,0.09200,0.092,150000.0,0.000,0.0,50000.0,6.0,0.0,760714940.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,20600.0,NaN,10572.718,0.0,0.0,44.0,NaN,370.80002,3773.600,34925.254,0.0,10572.718,0.0,0.0,0.0000,4664.00,0.0000,4316.44,0.0,NaN,77607.805,60602.0,0.0,0.0,10572.718,0.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,40000.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,44.0,0.0000,4316.44,10.0,35.0
1526655,2703451,91,0,10,5,NaN,NaN,-5591.0,NaN,324608.52,-25541.0,NaN,0.0,0.0,0.0,0.0,0.0,2fc785b2,a55475b1,a55475b1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,a55475b1,a55475b1,0.0,NaN,NaN,22904.6,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,NaN,1.0,2.0,0.0,301276.47,7088.6000,6191.6,0.0,0.0,5.0,0.0,0.0,5.0,-18.0,-12.0,-18.0,0.0,12553.2000,NaN,0.0,105129.310,15780.4,CA,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,21.0,0.0,100000.0,CAL,68098.4,68098.4,-1679.0,NaN,-128.0,2.0,0.0,40739.540,GBA,0.0,NaN,0.4000,NaN,NaN,-1679.0,-1876.0,2.0,NaN,CASH,0.4000,NaN,True,NaN,NaN,-364.0,-371.0,a55475b1,a55475b1,0.0,-371.0,a55475b1,-128.0,NaN,NaN,NaN,a55475b1,a55475b1,NaN,NaN,a55475b1,a55475b1,NaN,A,NaN,0.0,0.0,117251.600,NaN,0.0,2.0,2.0,202775.55,0.0,-128.0,7.0,2.0,2.0,0.0,2.0,2.0,2.0,40499.8000,116813.400,250031.200,40499.805,-92.0,-92.0,2.0,55.0,2.0,0.0,1.0,0.0,69.0,70.0,24.0,73.0,0.0,0.0,76.0,69.0,75.0,70.0,70.0,0.0,0.0,70.0,70.0,70.0,0.0,1.0,75.0,75.0,11.0,11.0,11.0,11.0,0.0,0.0,0.0,False,OTHER,OTHER,NaN,0.94595,0.00000,0.01351,0.00000,0.0000,24.0,0.0,0.0,0.0,P162_18_172,NaN,0.0,3.0,68098.4,68098.4,68098.4,701247.30,40499.805,FO,NaN,NaN,0.0,12809.2,90.000,0.0,90.00000,90.000,114000.0,59773.715,0.0,50000.0,1.0,68098.4,780594500.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64921.707,0.0,0.0,0.0,NaN,NaN,6191.600,34308.203,0.0,64921.707,0.0,0.0,0.0000,0.00,0.0000,0.00,NaN,NaN,121868.600,113980.0,0.0,0.0,64921.707,0.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27500.0,27477.6,0.0,0.0,0.0,0.0,36800.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1526656,2703452,91,0,10,5,NaN,NaN,NaN,NaN,102738.76,-15771.0,NaN,2.0,2.0,0.0,3.0,2.0,2fc785b2,a55475b1,a55475b1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,a55475b1,a55475b1,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,NaN,0.0,4.0,0.0,14232.40,7788.8003,0.0,0.0,0.0,0.0,0.0,0.0,3.0,-12.0,NaN,-16.0,1.0,2662.4001,NaN,NaN,NaN,1500.6,CA,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,60000.0,CAL,0.0,0.0,NaN,NaN,-569.0,4.0,0.0,60000.000,GBA,0.0,-350.0,0.4200,NaN,NaN,NaN,-720.0,0.0,NaN,CASH,0.4200,NaN,True,NaN,NaN,-409.0,-45.0,P159_130_59,P75_90_70,3998.0,-413.0,P180_60_137,-569.0,NaN,NaN,NaN,a55475b1,a55475b1,NaN,NaN,a55475b1,a55475b1,NaN,T,24000.0,0.0,0.0,6600.000,NaN,NaN,-27.0,NaN,17143.40,4.0,-597.0,5.0,0.0,4.0,0.0,0.0,0.0,4.0,3243.4001,4182.000,0.000,NaN,-27.0,-55.0,1.0,9.0,0.0,0.0,0.0,1.0,9.0,6.0,0.0,6.0,0.0,0.0,8.0,6.0,9.0,6.0,6.0,3.0,3.0,6.0,6.0,6.0,3.0,3.0,9.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,OTHER,OTHER,NaN,0.66667,0.00000,0.33333,0.11111,0.0000,11.0,0.0,0.0,0.0,P133_44_167,0.0,0.0,1.0,0.0,0.0,0.0,24002.00,NaN,BO,NaN,NaN,0.0,9048.0,NaN,0.0,NaN,NaN,80000.0,0.000,0.0,34000.0,1.0,0.0,NaN,2.0,NaN,NaN,15552.0,5.0,NaN,NaN,4000.0,53000.0,20547.752,0.0,15.0,0.0,4497.532,420.00000,4497.532,3242.800,0.0,NaN,0.0,0.0,4884.2983,0.00,4884.2983,0.00,0.0,20547.752,17143.400,NaN,0.0,0.0,20547.752,0.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30000.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,0.0,4884.2983,0.00,2.0,35.0

time: 9min 28s (started: 2024-04-06 22:21:08 -07:00)

## Overhaul 3: to_datetime() more

In [15]:
class Pipeline:
    @staticmethod
    def set_table_dtypes(df):
        for col in df.columns:
            if col in ["case_id", "WEEK_NUM", "num_group1", "num_group2"]:
                df.loc[:, col] = df.loc[:, col].astype('int32')
            elif col in ["date_decision"]:
                df.loc[:, col] = pd.to_datetime(df.loc[:, col]) #.astype('datetime64[ns]') #with_columns(pl.col(col).cast(pl.Date))
            elif col[-1] in ("P", "A"):
                df.loc[:, col] = df.loc[:, col].astype('float64') #with_columns(pl.col(col).cast(pl.Float64))
            elif col[-1] in ("M",):
                df.loc[:, col] = df.loc[:, col].astype('object') #.astype('string') #with_columns(pl.col(col).cast(pl.String))
            elif col[-1] in ("D",):
                df.loc[:, col] = pd.to_datetime(df.loc[:, col]) #.astype('datetime64[ns]') #with_columns(pl.col(col).cast(pl.Date))            

        return df
    
    @staticmethod
    def handle_dates(df):
        '''Edit date to number of days before the loan approval/refusal/denial decision date'''
        for col in df.columns:
            if col[-1] in ("D",):
                df.loc[:, col] = df.loc[:, col] - df.loc[:, 'date_decision'] #.with_columns(pl.col(col) - pl.col("date_decision"))
                df.loc[:, col] = df.loc[:, col].astype('timedelta64[D]') #df = df.with_columns(pl.col(col).dt.total_days())
                #with_columns(pl.col(col).cast(pl.Float32))
                
        return df.drop(columns=["date_decision", "MONTH"])

    
    @staticmethod
    def filter_cols(df):
        for col in df.columns:
            if col not in ["target", "case_id", "WEEK_NUM"]:
                isnull = df[col].isnull().mean()

                if isnull > 0.95:
                    df = df.drop(columns=col)

        for col in df.columns:
            if (col not in ["target", "case_id", "WEEK_NUM"]) & (df[col].dtype == object):
                freq = df[col].nunique()

                if (freq == 1) | (freq > 200):
                    df = df.drop(columns=col)

        return df



class Aggregator:
    @staticmethod
    def num_expr(df):
        '''P is for Transform DPD (Days past due); A is for Transform amount'''
        cols = [col for col in df.columns if col[-1] in ("P", "A")]

        return {col:'max' for col in cols}
   

    @staticmethod
    def date_expr(df):
        '''D is for Transform date'''
        cols = [col for col in df.columns if col[-1] in ("D",)]

        return {col:'max' for col in cols}

    @staticmethod
    def str_expr(df):
        '''M is for  Masking categories'''
        cols = [col for col in df.columns if col[-1] in ("M",)]
        
        return {col:'max' for col in cols}

    @staticmethod
    def other_expr(df):
        '''T is for Unspecified Transform; L is for Unspecified Transform'''
        cols = [col for col in df.columns if col[-1] in ("T", "L")]
        
        return {col:'max' for col in cols}

    
    @staticmethod
    def count_expr(df):
        cols = [col for col in df.columns if "num_group" in col]

        return {col:'max' for col in cols}
        

    @staticmethod
    def get_exprs(df):
        return {**Aggregator.num_expr(df),
                **Aggregator.date_expr(df), 
                #**Aggregator.str_expr(df), 
                #**Aggregator.other_expr(df),
                **Aggregator.count_expr(df)}

    
    @staticmethod    
    def get_cols_dictionary(df):
        exprs = Aggregator.get_exprs(df)
        cols = exprs.keys()
        cols_dictionary = {f'{col}':f'{exprs[col]}_{col}' for col in cols}
        print(f"cols_dictionary: {cols_dictionary}")
        return cols_dictionary

    
    

def read_file(path, depth=None):
    '''read in the file; the data type by column name or suffix'''
    df = pd.read_csv(path)
    df = df.pipe(Pipeline.set_table_dtypes)
    
    if depth in [1, 2]:
        df = df.groupby("case_id").agg(Aggregator.get_exprs(df)).rename(columns=Aggregator.get_cols_dictionary(df)) #df = df.groupby("case_id").agg(Aggregator.get_exprs(df))
    
    return df


def read_files(regex_path, depth=None):
    chunks = []
    for path in glob(str(regex_path)):
        df = pd.read_csv(path)
        df = df.pipe(Pipeline.set_table_dtypes)
        
        if depth in [1, 2]:
            df = df.groupby("case_id").agg(Aggregator.get_exprs(df)).rename(columns=Aggregator.get_cols_dictionary(df))

        
        chunks.append(df)
        
    df = pd.concat(chunks, axis=0)
    return df.drop_duplicates()





def feature_engineering(df_base, depth_0, depth_1, depth_2):
    
    #add 2 new columns
    df_base.loc[:, 'date_decision'] = pd.to_datetime(df_base.loc[:, 'date_decision'])
    df_base.loc[:, 'month_decision'] = df_base.loc[:, 'date_decision'].dt.month
    df_base.loc[:, 'day_decision'] = df_base.loc[:, 'date_decision'].dt.day
    #df_base = (df_base.with_columns(month_decision = pl.col("date_decision").dt.month(), weekday_decision = pl.col("date_decision").dt.weekday(),))

    
    #left join the DataFrame's in the list on 'case_id'
    for i, df in enumerate(depth_0 + depth_1 + depth_2):
        df_base = pd.merge(df_base, df, on='case_id', how='left', suffixes=("", f"_{i}")) #df_base = df_base.join(df, how="left", on="case_id", suffix=f"_{i}")
        
    df_base = df_base.pipe(Pipeline.handle_dates)
    
    return df_base




TRAIN_DIR = "../data/raw/train/"

data_store = {
    "df_base": read_file(TRAIN_DIR + "train_base.csv"),
    "depth_0": [
        read_file(TRAIN_DIR + "train_static_cb_0.csv"),
        read_files(TRAIN_DIR + "train_static_0_*.csv"),
    ],
    "depth_1": [
        read_files(TRAIN_DIR + "train_applprev_1_*.csv", 1),
        read_file(TRAIN_DIR + "train_tax_registry_a_1.csv", 1),
        read_file(TRAIN_DIR + "train_tax_registry_b_1.csv", 1),
        read_file(TRAIN_DIR + "train_tax_registry_c_1.csv", 1),
        read_files(TRAIN_DIR + "train_credit_bureau_a_1_*.csv", 1),
        read_file(TRAIN_DIR + "train_credit_bureau_b_1.csv", 1),
        read_file(TRAIN_DIR + "train_other_1.csv", 1),
        read_file(TRAIN_DIR + "train_person_1.csv", 1),
        read_file(TRAIN_DIR + "train_deposit_1.csv", 1),
        read_file(TRAIN_DIR + "train_debitcard_1.csv", 1),
    ],
    "depth_2": [
        read_file(TRAIN_DIR + "train_credit_bureau_b_2.csv", 2),
        read_files(TRAIN_DIR + "train_credit_bureau_a_2_*.csv", 2),
    ]
}



def preview_df(df):
    """Of this DataFrame, prints the row and column count and then returns the concatenated first 5 and last % rows.

    Args:
        df (DataFrame): This pandas DataFrame object.
    Returns:
        df (DataFrame): The concatenated first 5 and last 5 rows of this pandas DataFrame.
    """
    if df.shape[0] > 9:
        print(df.shape)
        return pd.DataFrame(pd.concat([df.head(5), df.tail(5)]))
    else:
        return df

    
#The *args will give you all positional arguments as a tuple
#The **kwargs will give you all keyword arguments as a dictionary

df_train = feature_engineering(**data_store)



preview_df(df_train)

/var/folders/77/y4hv4_s9751293nzv4yrfrtm0000gn/T/ipykernel_4499/4071992657.py:110: DtypeWarning: Columns (1,2,3,4,7,45,46,47,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/77/y4hv4_s9751293nzv4yrfrtm0000gn/T/ipykernel_4499/4071992657.py:122: DtypeWarning: Columns (20,45,46,56,57,84,143,146,167) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/77/y4hv4_s9751293nzv4yrfrtm0000gn/T/ipykernel_4499/4071992657.py:122: DtypeWarning: Columns (20,45,46,53,57,84,143,146,167) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/77/y4hv4_s9751293nzv4yrfrtm0000gn/T/ipykernel_4499/4071992657.py:122: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

cols_dictionary: {'actualdpd_943P': 'max_actualdpd_943P', 'annuity_853A': 'max_annuity_853A', 'credacc_actualbalance_314A': 'max_credacc_actualbalance_314A', 'credacc_credlmt_575A': 'max_credacc_credlmt_575A', 'credacc_maxhisbal_375A': 'max_credacc_maxhisbal_375A', 'credacc_minhisbal_90A': 'max_credacc_minhisbal_90A', 'credamount_590A': 'max_credamount_590A', 'currdebt_94A': 'max_currdebt_94A', 'downpmt_134A': 'max_downpmt_134A', 'mainoccupationinc_437A': 'max_mainoccupationinc_437A', 'maxdpdtolerance_577P': 'max_maxdpdtolerance_577P', 'outstandingdebt_522A': 'max_outstandingdebt_522A', 'revolvingaccount_394A': 'max_revolvingaccount_394A', 'approvaldate_319D': 'max_approvaldate_319D', 'creationdate_885D': 'max_creationdate_885D', 'dateactivated_425D': 'max_dateactivated_425D', 'dtlastpmt_581D': 'max_dtlastpmt_581D', 'dtlastpmtallstes_3545839D': 'max_dtlastpmtallstes_3545839D', 'employedfrom_700D': 'max_employedfrom_700D', 'firstnonzeroinstldate_307D': 'max_firstnonzeroinstldate_307D', 'num_group1': 'max_num_group1'}

/var/folders/77/y4hv4_s9751293nzv4yrfrtm0000gn/T/ipykernel_4499/4071992657.py:122: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

cols_dictionary: {'actualdpd_943P': 'max_actualdpd_943P', 'annuity_853A': 'max_annuity_853A', 'credacc_actualbalance_314A': 'max_credacc_actualbalance_314A', 'credacc_credlmt_575A': 'max_credacc_credlmt_575A', 'credacc_maxhisbal_375A': 'max_credacc_maxhisbal_375A', 'credacc_minhisbal_90A': 'max_credacc_minhisbal_90A', 'credamount_590A': 'max_credamount_590A', 'currdebt_94A': 'max_currdebt_94A', 'downpmt_134A': 'max_downpmt_134A', 'mainoccupationinc_437A': 'max_mainoccupationinc_437A', 'maxdpdtolerance_577P': 'max_maxdpdtolerance_577P', 'outstandingdebt_522A': 'max_outstandingdebt_522A', 'revolvingaccount_394A': 'max_revolvingaccount_394A', 'approvaldate_319D': 'max_approvaldate_319D', 'creationdate_885D': 'max_creationdate_885D', 'dateactivated_425D': 'max_dateactivated_425D', 'dtlastpmt_581D': 'max_dtlastpmt_581D', 'dtlastpmtallstes_3545839D': 'max_dtlastpmtallstes_3545839D', 'employedfrom_700D': 'max_employedfrom_700D', 'firstnonzeroinstldate_307D': 'max_firstnonzeroinstldate_307D', 'num_group1': 'max_num_group1'}
cols_dictionary: {'amount_4527230A': 'max_amount_4527230A', 'recorddate_4527225D': 'max_recorddate_4527225D', 'num_group1': 'max_num_group1'}
cols_dictionary: {'amount_4917619A': 'max_amount_4917619A', 'deductiondate_4917603D': 'max_deductiondate_4917603D', 'num_group1': 'max_num_group1'}
cols_dictionary: {'pmtamount_36A': 'max_pmtamount_36A', 'processingdate_168D': 'max_processingdate_168D', 'num_group1': 'max_num_group1'}
cols_dictionary: {'credlmt_230A': 'max_credlmt_230A', 'credlmt_935A': 'max_credlmt_935A', 'debtoutstand_525A': 'max_debtoutstand_525A', 'debtoverdue_47A': 'max_debtoverdue_47A', 'dpdmax_139P': 'max_dpdmax_139P', 'dpdmax_757P': 'max_dpdmax_757P', 'instlamount_768A': 'max_instlamount_768A', 'instlamount_852A': 'max_instlamount_852A', 'monthlyinstlamount_332A': 'max_monthlyinstlamount_332A', 'monthlyinstlamount_674A': 'max_monthlyinstlamount_674A', 'outstandingamount_354A': 'max_outstandingamount_354A', 'outstandingamount_362A': 'max_outstandingamount_362A', 'overdueamount_31A': 'max_overdueamount_31A', 'overdueamount_659A': 'max_overdueamount_659A', 'overdueamountmax2_14A': 'max_overdueamountmax2_14A', 'overdueamountmax2_398A': 'max_overdueamountmax2_398A', 'overdueamountmax_155A': 'max_overdueamountmax_155A', 'overdueamountmax_35A': 'max_overdueamountmax_35A', 'residualamount_488A': 'max_residualamount_488A', 'residualamount_856A': 'max_residualamount_856A', 'totalamount_6A': 'max_totalamount_6A', 'totalamount_996A': 'max_totalamount_996A', 'totaldebtoverduevalue_178A': 'max_totaldebtoverduevalue_178A', 'totaldebtoverduevalue_718A': 'max_totaldebtoverduevalue_718A', 'totaloutstanddebtvalue_39A': 'max_totaloutstanddebtvalue_39A', 'totaloutstanddebtvalue_668A': 'max_totaloutstanddebtvalue_668A', 'dateofcredend_289D': 'max_dateofcredend_289D', 'dateofcredend_353D': 'max_dateofcredend_353D', 'dateofcredstart_181D': 'max_dateofcredstart_181D', 'dateofcredstart_739D': 'max_dateofcredstart_739D', 'dateofrealrepmt_138D': 'max_dateofrealrepmt_138D', 'lastupdate_1112D': 'max_lastupdate_1112D', 'lastupdate_388D': 'max_lastupdate_388D', 'numberofoverdueinstlmaxdat_148D': 'max_numberofoverdueinstlmaxdat_148D', 'numberofoverdueinstlmaxdat_641D': 'max_numberofoverdueinstlmaxdat_641D', 'overdueamountmax2date_1002D': 'max_overdueamountmax2date_1002D', 'overdueamountmax2date_1142D': 'max_overdueamountmax2date_1142D', 'refreshdate_3813885D': 'max_refreshdate_3813885D', 'num_group1': 'max_num_group1'}
cols_dictionary: {'credlmt_230A': 'max_credlmt_230A', 'credlmt_935A': 'max_credlmt_935A', 'debtoutstand_525A': 'max_debtoutstand_525A', 'debtoverdue_47A': 'max_debtoverdue_47A', 'dpdmax_139P': 'max_dpdmax_139P', 'dpdmax_757P': 'max_dpdmax_757P', 'instlamount_768A': 'max_instlamount_768A', 'instlamount_852A': 'max_instlamount_852A', 'monthlyinstlamount_332A': 'max_monthlyinstlamount_332A', 'monthlyinstlamount_674A': 'max_monthlyinstlamount_674A', 'outstandingamount_354A': 'max_outstandingamount_354A', 'outstandingamount_362A': 'max_outstandingamount_362A', 'overdueamount_31A': 'max_overdueamount_31A', 'overdueamount_659A': 'max_overdueamount_659A', 'overdueamountmax2_14A': 'max_overdueamountmax2_14A', 'overdueamountmax2_398A': 'max_overdueamountmax2_398A', 'overdueamountmax_155A': 'max_overdueamountmax_155A', 'overdueamountmax_35A': 'max_overdueamountmax_35A', 'residualamount_488A': 'max_residualamount_488A', 'residualamount_856A': 'max_residualamount_856A', 'totalamount_6A': 'max_totalamount_6A', 'totalamount_996A': 'max_totalamount_996A', 'totaldebtoverduevalue_178A': 'max_totaldebtoverduevalue_178A', 'totaldebtoverduevalue_718A': 'max_totaldebtoverduevalue_718A', 'totaloutstanddebtvalue_39A': 'max_totaloutstanddebtvalue_39A', 'totaloutstanddebtvalue_668A': 'max_totaloutstanddebtvalue_668A', 'dateofcredend_289D': 'max_dateofcredend_289D', 'dateofcredend_353D': 'max_dateofcredend_353D', 'dateofcredstart_181D': 'max_dateofcredstart_181D', 'dateofcredstart_739D': 'max_dateofcredstart_739D', 'dateofrealrepmt_138D': 'max_dateofrealrepmt_138D', 'lastupdate_1112D': 'max_lastupdate_1112D', 'lastupdate_388D': 'max_lastupdate_388D', 'numberofoverdueinstlmaxdat_148D': 'max_numberofoverdueinstlmaxdat_148D', 'numberofoverdueinstlmaxdat_641D': 'max_numberofoverdueinstlmaxdat_641D', 'overdueamountmax2date_1002D': 'max_overdueamountmax2date_1002D', 'overdueamountmax2date_1142D': 'max_overdueamountmax2date_1142D', 'refreshdate_3813885D': 'max_refreshdate_3813885D', 'num_group1': 'max_num_group1'}

/var/folders/77/y4hv4_s9751293nzv4yrfrtm0000gn/T/ipykernel_4499/4071992657.py:122: DtypeWarning: Columns (11,12,14,30,44,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

cols_dictionary: {'credlmt_230A': 'max_credlmt_230A', 'credlmt_935A': 'max_credlmt_935A', 'debtoutstand_525A': 'max_debtoutstand_525A', 'debtoverdue_47A': 'max_debtoverdue_47A', 'dpdmax_139P': 'max_dpdmax_139P', 'dpdmax_757P': 'max_dpdmax_757P', 'instlamount_768A': 'max_instlamount_768A', 'instlamount_852A': 'max_instlamount_852A', 'monthlyinstlamount_332A': 'max_monthlyinstlamount_332A', 'monthlyinstlamount_674A': 'max_monthlyinstlamount_674A', 'outstandingamount_354A': 'max_outstandingamount_354A', 'outstandingamount_362A': 'max_outstandingamount_362A', 'overdueamount_31A': 'max_overdueamount_31A', 'overdueamount_659A': 'max_overdueamount_659A', 'overdueamountmax2_14A': 'max_overdueamountmax2_14A', 'overdueamountmax2_398A': 'max_overdueamountmax2_398A', 'overdueamountmax_155A': 'max_overdueamountmax_155A', 'overdueamountmax_35A': 'max_overdueamountmax_35A', 'residualamount_488A': 'max_residualamount_488A', 'residualamount_856A': 'max_residualamount_856A', 'totalamount_6A': 'max_totalamount_6A', 'totalamount_996A': 'max_totalamount_996A', 'totaldebtoverduevalue_178A': 'max_totaldebtoverduevalue_178A', 'totaldebtoverduevalue_718A': 'max_totaldebtoverduevalue_718A', 'totaloutstanddebtvalue_39A': 'max_totaloutstanddebtvalue_39A', 'totaloutstanddebtvalue_668A': 'max_totaloutstanddebtvalue_668A', 'dateofcredend_289D': 'max_dateofcredend_289D', 'dateofcredend_353D': 'max_dateofcredend_353D', 'dateofcredstart_181D': 'max_dateofcredstart_181D', 'dateofcredstart_739D': 'max_dateofcredstart_739D', 'dateofrealrepmt_138D': 'max_dateofrealrepmt_138D', 'lastupdate_1112D': 'max_lastupdate_1112D', 'lastupdate_388D': 'max_lastupdate_388D', 'numberofoverdueinstlmaxdat_148D': 'max_numberofoverdueinstlmaxdat_148D', 'numberofoverdueinstlmaxdat_641D': 'max_numberofoverdueinstlmaxdat_641D', 'overdueamountmax2date_1002D': 'max_overdueamountmax2date_1002D', 'overdueamountmax2date_1142D': 'max_overdueamountmax2date_1142D', 'refreshdate_3813885D': 'max_refreshdate_3813885D', 'num_group1': 'max_num_group1'}
cols_dictionary: {'credlmt_230A': 'max_credlmt_230A', 'credlmt_935A': 'max_credlmt_935A', 'debtoutstand_525A': 'max_debtoutstand_525A', 'debtoverdue_47A': 'max_debtoverdue_47A', 'dpdmax_139P': 'max_dpdmax_139P', 'dpdmax_757P': 'max_dpdmax_757P', 'instlamount_768A': 'max_instlamount_768A', 'instlamount_852A': 'max_instlamount_852A', 'monthlyinstlamount_332A': 'max_monthlyinstlamount_332A', 'monthlyinstlamount_674A': 'max_monthlyinstlamount_674A', 'outstandingamount_354A': 'max_outstandingamount_354A', 'outstandingamount_362A': 'max_outstandingamount_362A', 'overdueamount_31A': 'max_overdueamount_31A', 'overdueamount_659A': 'max_overdueamount_659A', 'overdueamountmax2_14A': 'max_overdueamountmax2_14A', 'overdueamountmax2_398A': 'max_overdueamountmax2_398A', 'overdueamountmax_155A': 'max_overdueamountmax_155A', 'overdueamountmax_35A': 'max_overdueamountmax_35A', 'residualamount_488A': 'max_residualamount_488A', 'residualamount_856A': 'max_residualamount_856A', 'totalamount_6A': 'max_totalamount_6A', 'totalamount_996A': 'max_totalamount_996A', 'totaldebtoverduevalue_178A': 'max_totaldebtoverduevalue_178A', 'totaldebtoverduevalue_718A': 'max_totaldebtoverduevalue_718A', 'totaloutstanddebtvalue_39A': 'max_totaloutstanddebtvalue_39A', 'totaloutstanddebtvalue_668A': 'max_totaloutstanddebtvalue_668A', 'dateofcredend_289D': 'max_dateofcredend_289D', 'dateofcredend_353D': 'max_dateofcredend_353D', 'dateofcredstart_181D': 'max_dateofcredstart_181D', 'dateofcredstart_739D': 'max_dateofcredstart_739D', 'dateofrealrepmt_138D': 'max_dateofrealrepmt_138D', 'lastupdate_1112D': 'max_lastupdate_1112D', 'lastupdate_388D': 'max_lastupdate_388D', 'numberofoverdueinstlmaxdat_148D': 'max_numberofoverdueinstlmaxdat_148D', 'numberofoverdueinstlmaxdat_641D': 'max_numberofoverdueinstlmaxdat_641D', 'overdueamountmax2date_1002D': 'max_overdueamountmax2date_1002D', 'overdueamountmax2date_1142D': 'max_overdueamountmax2date_1142D', 'refreshdate_3813885D': 'max_refreshdate_3813885D', 'num_group1': 'max_num_group1'}

/var/folders/77/y4hv4_s9751293nzv4yrfrtm0000gn/T/ipykernel_4499/4071992657.py:110: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

cols_dictionary: {'amount_1115A': 'max_amount_1115A', 'credlmt_1052A': 'max_credlmt_1052A', 'credlmt_228A': 'max_credlmt_228A', 'credlmt_3940954A': 'max_credlmt_3940954A', 'debtpastduevalue_732A': 'max_debtpastduevalue_732A', 'debtvalue_227A': 'max_debtvalue_227A', 'dpd_550P': 'max_dpd_550P', 'dpd_733P': 'max_dpd_733P', 'dpdmax_851P': 'max_dpdmax_851P', 'installmentamount_644A': 'max_installmentamount_644A', 'installmentamount_833A': 'max_installmentamount_833A', 'instlamount_892A': 'max_instlamount_892A', 'maxdebtpduevalodued_3940955A': 'max_maxdebtpduevalodued_3940955A', 'overdueamountmax_950A': 'max_overdueamountmax_950A', 'pmtdaysoverdue_1135P': 'max_pmtdaysoverdue_1135P', 'residualamount_1093A': 'max_residualamount_1093A', 'residualamount_127A': 'max_residualamount_127A', 'residualamount_3940956A': 'max_residualamount_3940956A', 'totalamount_503A': 'max_totalamount_503A', 'totalamount_881A': 'max_totalamount_881A', 'contractdate_551D': 'max_contractdate_551D', 'contractmaturitydate_151D': 'max_contractmaturitydate_151D', 'lastupdate_260D': 'max_lastupdate_260D', 'num_group1': 'max_num_group1'}
cols_dictionary: {'amtdebitincoming_4809443A': 'max_amtdebitincoming_4809443A', 'amtdebitoutgoing_4809440A': 'max_amtdebitoutgoing_4809440A', 'amtdepositbalance_4809441A': 'max_amtdepositbalance_4809441A', 'amtdepositincoming_4809444A': 'max_amtdepositincoming_4809444A', 'amtdepositoutgoing_4809442A': 'max_amtdepositoutgoing_4809442A', 'num_group1': 'max_num_group1'}

/var/folders/77/y4hv4_s9751293nzv4yrfrtm0000gn/T/ipykernel_4499/4071992657.py:110: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

cols_dictionary: {'mainoccupationinc_384A': 'max_mainoccupationinc_384A', 'birth_259D': 'max_birth_259D', 'birthdate_87D': 'max_birthdate_87D', 'empl_employedfrom_271D': 'max_empl_employedfrom_271D', 'num_group1': 'max_num_group1'}
cols_dictionary: {'amount_416A': 'max_amount_416A', 'contractenddate_991D': 'max_contractenddate_991D', 'openingdate_313D': 'max_openingdate_313D', 'num_group1': 'max_num_group1'}
cols_dictionary: {'last180dayaveragebalance_704A': 'max_last180dayaveragebalance_704A', 'last180dayturnover_1134A': 'max_last180dayturnover_1134A', 'last30dayturnover_651A': 'max_last30dayturnover_651A', 'openingdate_857D': 'max_openingdate_857D', 'num_group1': 'max_num_group1'}
cols_dictionary: {'pmts_dpdvalue_108P': 'max_pmts_dpdvalue_108P', 'pmts_pmtsoverdue_635A': 'max_pmts_pmtsoverdue_635A', 'pmts_date_1107D': 'max_pmts_date_1107D', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
cols_dictionary: {'pmts_dpd_1073P': 'max_pmts_dpd_1073P', 'pmts_dpd_303P': 'max_pmts_dpd_303P', 'pmts_overdue_1140A': 'max_pmts_overdue_1140A', 'pmts_overdue_1152A': 'max_pmts_overdue_1152A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
cols_dictionary: {'pmts_dpd_1073P': 'max_pmts_dpd_1073P', 'pmts_dpd_303P': 'max_pmts_dpd_303P', 'pmts_overdue_1140A': 'max_pmts_overdue_1140A', 'pmts_overdue_1152A': 'max_pmts_overdue_1152A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
cols_dictionary: {'pmts_dpd_1073P': 'max_pmts_dpd_1073P', 'pmts_dpd_303P': 'max_pmts_dpd_303P', 'pmts_overdue_1140A': 'max_pmts_overdue_1140A', 'pmts_overdue_1152A': 'max_pmts_overdue_1152A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
cols_dictionary: {'pmts_dpd_1073P': 'max_pmts_dpd_1073P', 'pmts_dpd_303P': 'max_pmts_dpd_303P', 'pmts_overdue_1140A': 'max_pmts_overdue_1140A', 'pmts_overdue_1152A': 'max_pmts_overdue_1152A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
cols_dictionary: {'pmts_dpd_1073P': 'max_pmts_dpd_1073P', 'pmts_dpd_303P': 'max_pmts_dpd_303P', 'pmts_overdue_1140A': 'max_pmts_overdue_1140A', 'pmts_overdue_1152A': 'max_pmts_overdue_1152A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
cols_dictionary: {'pmts_dpd_1073P': 'max_pmts_dpd_1073P', 'pmts_dpd_303P': 'max_pmts_dpd_303P', 'pmts_overdue_1140A': 'max_pmts_overdue_1140A', 'pmts_overdue_1152A': 'max_pmts_overdue_1152A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
cols_dictionary: {'pmts_dpd_1073P': 'max_pmts_dpd_1073P', 'pmts_dpd_303P': 'max_pmts_dpd_303P', 'pmts_overdue_1140A': 'max_pmts_overdue_1140A', 'pmts_overdue_1152A': 'max_pmts_overdue_1152A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
cols_dictionary: {'pmts_dpd_1073P': 'max_pmts_dpd_1073P', 'pmts_dpd_303P': 'max_pmts_dpd_303P', 'pmts_overdue_1140A': 'max_pmts_overdue_1140A', 'pmts_overdue_1152A': 'max_pmts_overdue_1152A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
cols_dictionary: {'pmts_dpd_1073P': 'max_pmts_dpd_1073P', 'pmts_dpd_303P': 'max_pmts_dpd_303P', 'pmts_overdue_1140A': 'max_pmts_overdue_1140A', 'pmts_overdue_1152A': 'max_pmts_overdue_1152A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
cols_dictionary: {'pmts_dpd_1073P': 'max_pmts_dpd_1073P', 'pmts_dpd_303P': 'max_pmts_dpd_303P', 'pmts_overdue_1140A': 'max_pmts_overdue_1140A', 'pmts_overdue_1152A': 'max_pmts_overdue_1152A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
cols_dictionary: {'pmts_dpd_1073P': 'max_pmts_dpd_1073P', 'pmts_dpd_303P': 'max_pmts_dpd_303P', 'pmts_overdue_1140A': 'max_pmts_overdue_1140A', 'pmts_overdue_1152A': 'max_pmts_overdue_1152A', 'num_group1': 'max_num_group1', 'num_group2': 'max_num_group2'}
(1526659, 348)

,case_id,WEEK_NUM,target,month_decision,day_decision,assignmentdate_238D,assignmentdate_4527235D,assignmentdate_4955616D,birthdate_574D,contractssum_5085716L,dateofbirth_337D,dateofbirth_342D,days120_123L,days180_256L,days30_165L,days360_512L,days90_310L,description_5085714M,education_1103M,education_88M,firstquarter_103L,for3years_128L,for3years_504L,for3years_584L,formonth_118L,formonth_206L,formonth_535L,forquarter_1017L,forquarter_462L,forquarter_634L,fortoday_1092L,forweek_1077L,forweek_528L,forweek_601L,foryear_618L,foryear_818L,foryear_850L,fourthquarter_440L,maritalst_385M,maritalst_893M,numberofqueries_373L,pmtaverage_3A,pmtaverage_4527227A,pmtaverage_4955615A,pmtcount_4527229L,pmtcount_4955617L,pmtcount_693L,pmtscount_423L,pmtssum_45A,requesttype_4525192L,responsedate_1012D,responsedate_4527233D,responsedate_4917613D,riskassesment_302T,riskassesment_940T,secondquarter_766L,thirdquarter_1082L,actualdpdtolerance_344P,amtinstpaidbefduel24m_4187115A,annuity_780A,annuitynextmonth_57A,applicationcnt_361L,applications30d_658L,applicationscnt_1086L,applicationscnt_464L,applicationscnt_629L,applicationscnt_867L,avgdbddpdlast24m_3658932P,avgdbddpdlast3m_4187120P,avgdbdtollast24m_4525197P,avgdpdtolclosure24_3658938P,avginstallast24m_3658937A,avglnamtstart24m_4525187A,avgmaxdpdlast9m_3716943P,avgoutstandbalancel6m_4187114A,avgpmtlast12m_4525200A,bankacctype_710L,cardtype_51L,clientscnt12m_3712952L,clientscnt3m_3712950L,clientscnt6m_3712949L,clientscnt_100L,clientscnt_1022L,clientscnt_1071L,clientscnt_1130L,clientscnt_136L,clientscnt_157L,clientscnt_257L,clientscnt_304L,clientscnt_360L,clientscnt_493L,clientscnt_533L,clientscnt_887L,clientscnt_946L,cntincpaycont9m_3716944L,cntpmts24_3658933L,commnoinclast6m_3546845L,credamount_770A,credtype_322L,currdebt_22A,currdebtcredtyperange_828A,datefirstoffer_1144D,datelastinstal40dpd_247D,datelastunpaid_3546854D,daysoverduetolerancedd_3976961L,deferredmnthsnum_166L,disbursedcredamount_1113A,disbursementtype_67L,downpmt_116A,dtlastpmtallstes_4499206D,eir_270L,equalitydataagreement_891L,equalityempfrom_62L,firstclxcampaign_1125D,firstdatedue_489D,homephncnt_628L,inittransactionamount_650A,inittransactioncode_186L,interestrate_311L,interestrategrace_34L,isbidproduct_1095L,isbidproductrequest_292L,isdebitcard_729L,lastactivateddate_801D,lastapplicationdate_877D,lastapprcommoditycat_1041M,lastapprcommoditytypec_5251766M,lastapprcredamount_781A,lastapprdate_640D,lastcancelreason_561M,lastdelinqdate_224D,lastdependentsnum_448L,lastotherinc_902A,lastotherlnsexpense_631A,lastrejectcommoditycat_161M,lastrejectcommodtypec_5251769M,lastrejectcredamount_222A,lastrejectdate_50D,lastrejectreason_759M,lastrejectreasonclient_4145040M,lastrepayingdate_696D,lastst_736L,maininc_215A,mastercontrelectronic_519L,mastercontrexist_109L,maxannuity_159A,maxannuity_4075009A,maxdbddpdlast1m_3658939P,maxdbddpdtollast12m_3658940P,maxdbddpdtollast6m_4187119P,maxdebt4_972A,maxdpdfrom6mto36m_3546853P,maxdpdinstldate_3546855D,maxdpdinstlnum_3546846P,maxdpdlast12m_727P,maxdpdlast24m_143P,maxdpdlast3m_392P,maxdpdlast6m_474P,maxdpdlast9m_1059P,maxdpdtolerance_374P,maxinstallast24m_3658928A,maxlnamtstart6m_4525199A,maxoutstandbalancel12m_4187113A,maxpmtlast3m_4525190A,mindbddpdlast24m_3658935P,mindbdtollast24m_4525191P,mobilephncnt_593L,monthsannuity_845L,numactivecreds_622L,numactivecredschannel_414L,numactiverelcontr_750L,numcontrs3months_479L,numincomingpmts_3546848L,numinstlallpaidearly3d_817L,numinstls_657L,numinstlsallpaid_934L,numinstlswithdpd10_728L,numinstlswithdpd5_4187116L,numinstlswithoutdpd_562L,numinstmatpaidtearly2d_4499204L,numinstpaid_4499208L,numinstpaidearly3d_3546850L,numinstpaidearly3dest_4493216L,numinstpaidearly5d_1087L,numinstpaidearly5dest_4493211L,numinstpaidearly5dobd_4499205L,numinstpaidearly_338L,numinstpaidearlyest_4493214L,numinstpaidlastcontr_4325080L,numinstpaidlate1d_3546852L,numinstregularpaid_973L,numinstregularpaidest_4493210L,numinsttopaygr_769L,numinsttopaygrest_4493213L,numinstunpaidmax_3546851L,numinstunpaidmaxest_4493212L,numnotactivated_1143L,numpmtchanneldd_318L,numrejects9m_859L,opencred_647L,paytype1st_925L,paytype_783L,payvacationpostpone_4187118D,pctinstlsallpaidearl3d_427L,pctinstlsallpaidlat10d_839L,pctinstlsallpaidlate1d_3546856L,pctinstlsallpaidlate4d_3546849L,pctinstlsallpaidlate6d_3546844L,pmtnum_254L,posfpd10lastmonth_333P,posfpd30lastmonth_3976960P,posfstqpd30lastmonth_3976962P,previouscontdistrict_112M,price_1097A,sellerplacecnt_915L,sellerplacescnt_216L,sumoutstandtotal_3546847A,sumoutstandtotalest_4493215A,totaldebt_9A,totalsettled_863A,totinstallast1m_4525188A,twobodfilling_608L,typesuite_864L,validfrom_1069D,max_actualdpd_943P,max_annuity_853A,max_credacc_actualbalance_314A,max_credacc_credlmt_575A,max_credacc_maxhisbal_375A,max_credacc_minhisbal_90A,max_credamount_590A,max_currdebt_94A,max_downpmt_134A,max_mainoccupationinc_437A,max_maxdpdtolerance_577P,max_outstandingdebt_522A,max_revolvingaccount_394A,max_approvaldate_319D,max_creationdate_885D,max_dateactivated_425D,max_dtlastpmt_581D,max_dtlastpmtallstes_3545839D,max_employedfrom_700D,max_firstnonzeroinstldate_307D,max_num_group1,max_amount_4527230A,max_recorddate_4527225D,max_num_group1_3,max_amount_4917619A,max_deductiondate_4917603D,max_num_group1_4,max_pmtamount_36A,max_processingdate_168D,max_num_group1_5,max_credlmt_230A,max_credlmt_935A,max_debtoutstand_525A,max_debtoverdue_47A,max_dpdmax_139P,max_dpdmax_757P,max_instlamount_768A,max_instlamount_852A,max_monthlyinstlamount_332A,max_monthlyinstlamount_674A,max_outstandingamount_354A,max_outstandingamount_362A,max_overdueamount_31A,max_overdueamount_659A,max_overdueamountmax2_14A,max_overdueamountmax2_398A,max_overdueamountmax_155A,max_overdueamountmax_35A,max_residualamount_488A,max_residualamount_856A,max_totalamount_6A,max_totalamount_996A,max_totaldebtoverduevalue_178A,max_totaldebtoverduevalue_718A,max_totaloutstanddebtvalue_39A,max_totaloutstanddebtvalue_668A,max_dateofcredend_289D,max_dateofcredend_353D,max_dateofcredstart_181D,max_dateofcredstart_739D,max_dateofrealrepmt_138D,max_lastupdate_1112D,max_lastupdate_388D,max_numberofoverdueinstlmaxdat_148D,max_numberofoverdueinstlmaxdat_641D,max_overdueamountmax2date_1002D,max_overdueamountmax2date_1142D,max_refreshdate_3813885D,max_num_group1_6,max_amount_1115A,max_credlmt_1052A,max_credlmt_228A,max_credlmt_3940954A,max_debtpastduevalue_732A,max_debtvalue_227A,max_dpd_550P,max_dpd_733P,max_dpdmax_851P,max_installmentamount_644A,max_installmentamount_833A,max_instlamount_892A,max_maxdebtpduevalodued_3940955A,max_overdueamountmax_950A,max_pmtdaysoverdue_1135P,max_residualamount_1093A,max_residualamount_127A,max_residualamount_3940956A,max_totalamount_503A,max_totalamount_881A,max_contractdate_551D,max_contractmaturitydate_151D,max_lastupdate_260D,max_num_group1_7,max_amtdebitincoming_4809443A,max_amtdebitoutgoing_4809440A,max_amtdepositbalance_4809441A,max_amtdepositincoming_4809444A,max_amtdepositoutgoing_4809442A,max_num_group1_8,max_mainoccupationinc_384A,max_birth_259D,max_birthdate_87D,max_empl_employedfrom_271D,max_num_group1_9,max_amount_416A,max_contractenddate_991D,max_openingdate_313D,max_num_group1_10,max_last180dayaveragebalance_704A,max_last180dayturnover_1134A,max_last30dayturnover_651A,max_openingdate_857D,max_num_group1_11,max_pmts_dpdvalue_108P,max_pmts_pmtsoverdue_635A,max_pmts_date_1107D,max_num_group1_12,max_num_group2,max_pmts_dpd_1073P,max_pmts_dpd_303P,max_pmts_overdue_1140A,max_pmts_overdue_1152A,max_num_group1_13,max_num_group2_13
0,0,0,0,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1917.6000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,30000.0,CAL,0.0,0.0,NaN,NaN,NaN,NaN,0.0,30000.000,GBA,0.0,NaN,0.4500,NaN,NaN,NaN,NaN,0.0,NaN,CASH,0.4500,NaN,False,NaN,NaN,NaN,NaN,a55475b1,a55475b1,NaN,NaN,a55475b1,NaN,NaN,NaN,NaN,a55475b1,a55475b1,NaN,NaN,a55475b1,a55475b1,NaN,NaN,NaN,0.0,0.0,0.000,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,OTHER,OTHER,NaN,NaN,NaN,NaN,NaN,NaN,24.0,0.0,0.0,NaN,a55475b1,NaN,0.0,0.0,NaN,NaN,0.0,0.00,NaN,BO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10800.0,-11874.0,NaN,-475.0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0,0,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3134.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,19999.8,CAL,0.0,0.0,NaN,NaN,NaN,NaN,0.0,19999.800,GBA,0.0,NaN,0.2999,NaN,NaN,NaN,NaN,0.0,NaN,CASH,0.2999,0.0,False,NaN,NaN,NaN,NaN,a55475b1,a55475b1,NaN,NaN,a55475b1,NaN,NaN,NaN,NaN,a55475b1,a55475b1,NaN,NaN,a55475b1,a55475b1,NaN,NaN,NaN,0.0,0.0,0.000,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,OTHER,OTHER,NaN,NaN,NaN,NaN,NaN,NaN,18.0,0.0,0.0,NaN,a55475b1,NaN,0.0,0.0,NaN,NaN,0.0,0.00,NaN,BO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10000.0,-22435.0,NaN,-3718.0,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,0,0,1,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4937.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,78000.0,CAL,0.0,0.0,NaN,NaN,NaN,NaN,0.0,78000.000,GBA,0.0,NaN,0.4500,NaN,NaN,NaN,NaN,1.0,NaN,CASH,0.4500,NaN,False,NaN,NaN,NaN,-2102.0,a55475b1,a55475b1,NaN,NaN,a55475b1,NaN,NaN,NaN,NaN,a55475b1,a55475b1,10000.0,-2102.0,a55475b1,a55475b1,NaN,D,NaN,0.0,0.0,0.000,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,False,OTHER,OTHER,NaN,NaN,NaN,NaN,NaN,NaN,36.0,0.0,0.0,NaN,a55475b1,NaN,0.0,0.0,NaN,NaN,0.0,0.00,NaN,BO,AL,NaN,0.0,1682.4,NaN,0.0,NaN,NaN,16000.0,NaN,0.0,8200.0,NaN,NaN,NaN,NaN,-2102.0,NaN,NaN,NaN,-3245.0,-2071.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14000.0,-16105.0,NaN,-3245.0,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,0,0,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4643.6000,0.0,0.0,1.0,0.0,2.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,40000.0,CAL,0.0,0.0,NaN,NaN,NaN,NaN,0.0,40000.000,GBA,0.0,NaN,0.4200,True,True,NaN,NaN,0.0,NaN,CASH,0.4200,0.0,False,NaN,NaN,NaN,4.0,a55475b1,a55475b1,NaN,NaN,P94_109_143,NaN,NaN,NaN,NaN,a55475b1,a55475b1,59999.8,4.0,P94_109_143,a55475b1,NaN,D,NaN,0.0,0.0,0.000,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.0,0.0,0.0,1.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,False,OTHER,OTHER,NaN,NaN,NaN,NaN,NaN,NaN,12.0,0.0,0.0,NaN,a55475b1,NaN,1.0,1.0,NaN,NaN,0.0,0.00,NaN,BO,AL,NaN,0.0,6140.0,NaN,0.0,NaN,NaN,59999.8,NaN,0.0,11000.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,-233.0,35.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10000.0,-9286.0,NaN,-233.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,0,1,1,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3390.2000,0.0,0.0,1.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,44000.0,CAL,0.0,0.0,NaN,NaN,NaN,NaN,0.0,44000.000,GBA,0.0,NaN,0.4500,NaN,NaN,NaN,NaN,1.0,NaN,CASH,0.4500,NaN,False,NaN,NaN,NaN,4.0,a55475b1,a55475b1,NaN,NaN,P24_27_36,NaN,NaN,NaN,NaN,a55475b1,a55475b1,NaN,NaN,a55475b1,a55475b1,NaN,T,NaN,0.0,0.0,0.000,NaN,NaN,NaN,NaN,0.00,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,False,OTHER,OTHER,NaN,NaN,NaN,NaN,NaN,NaN,24.0,0.0,0.0,NaN,a55475b1,NaN,0.0,0.0,NaN,NaN,0.0,0.00,NaN,BO,AL,NaN,0.0,2556.6,NaN,0.0,NaN,NaN,40000.0,NaN,0.0,16000.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,35.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24000.0,-9134.0,NaN,-1481.0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1526654,2703450,91,0,10,5,NaN,NaN,-998.0,NaN,52863.59,-22193.0,NaN,0.0,0.0,0.0,0.0,0.0,2fc785b2,a55475b1,a55475b1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,a55475b1,a55475b1,0.0,NaN,NaN,12155.0,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,NaN,1.0,1.0,0.0,176561.36,3675.4001,0.0,0.0,0.0,0.0,0.0,0.0,10.0,-23.0,-43.0,-23.0,0.0,7356.8003,NaN,0.0,16392.496,6750.2,CA,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,24.0,0.0,30000.0,CAL,0.0,0.0,-2785.0,NaN,-1481.0,8.0,0.0,30000.000,GBA,0.0,NaN,0.4200,NaN,NaN,-1610.0,-4833.0,0.0,NaN,CASH,0.4200,NaN,True,NaN,NaN,-355.0,-362.0,P12_6_178,P142_50_170,20020.0,-362.0,a55475b1,-1481.0,NaN,NaN,NaN,a55475b1,a55475b1,150000.0,-1040.0,P94_109_143,P94_109_143,NaN,K,36000.0,0.0,0.0,75521.910,NaN,0.0,0.0,0.0,105019.79,0.0,-1512.0,6.0,0.0,0.0,0.0,0.0,0.0,8.0,46718.2000,49651.402,77533.760,14346.319,-144.0,-144.0,3.0,65.0,1.0,0.0,1.0,0.0,92.0,106.0,0.0,112.0,0.0,1.0,117.0,106.0,113.0,103.0,103.0,11.0,11.0,99.0,99.0,99.0,12.0,4.0,113.0,113.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,OTHER,OTHER,NaN,0.91150,0.02655,0.03540,0.03540,0.0354,12.0,0.0,0.0,0.0,P123_39_170,0.0,0.0,8.0,0.0,0.0,0.0,428159.66,14346.319,FO,NaN,NaN,0.0,30875.0,0.092,0.0,0.09200,0.092,150000.0,0.000,0.0,50000.0,6.0,0.0,760714940.0,-362.0,-362.0,-355.0,3.0,3.0,-2090.0,-332.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20600.0,NaN,10572.718,0.0,0.0,44.0,NaN,370.80002,3773.600,34925.254,0.0,10572.718,0.0,0.0,0.0000,4664.00,0.0000,4316.44,0.0,NaN,77607.805,60602.0,0.0,0.0,10572.718,0.0,94.0,-27.0,-362.0,-637.0,-26.0,3.0,-26.0,-1482.0,NaN,-1482.0,NaN,14.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,40000.0,-22193.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,44.0,0.0000,4316.44,10.0,35.0
1526655,2703451,91,0,10,5,NaN,NaN,-5591.0,NaN,324608.52,-25541.0,NaN,0.0,0.0,0.0,0.0,0.0,2fc785b2,a55475b1,a55475b1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,a55475b1,a55475b1,0.0,NaN,NaN,22904.6,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,NaN,1.0,2.0,0.0,301276.47,7088.6000,6191.6,0.0,0.0,5.0,0.0,0.0,5.0,-18.0,-12.0,-18.0,0.0,12553.2000,NaN,0.0,105129.310,15780.4,CA,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,21.0,0.0,100000.0,CAL,68098.4,68098.4,-1679.0,NaN,-128.0,2.0,0.0,40739.540,GBA,0.0,NaN,0.4000,NaN,NaN,-1679.0,-1876.0,2.0,NaN,CASH,0.4000,NaN,True,NaN,NaN,-364.0,-371.0,a55475b1,a55475b1,0.0,-371.0,a55475b1,-128.0,NaN,NaN,NaN,a55475b1,a55475b1,NaN,NaN,a55475b1,a55475b1,NaN,A,NaN,0.0,0.0,117251.600,NaN,0.0,2.0,2.0,202775.55,0.0,-128.0,7.0,2.0,2.0,0.0,2.0,2.0,2.0,40499.8000,116813.400,250031.200,40499.805,-92.0,-92.0,2.0,55.0,2.0,0.0,1.0,0.0,69.0,70.0,24.0,73.0,0.0,0.0,76.0,69.0,75.0,70.0,70.0,0.0,0.0,70.0,70.0,70.0,0.0,1.0,75.0,75.0,11.0,11.0,11.0,11.0,0.0,0.0,0.0,False,OTHER,OTHER,NaN,0.94595,0.00000,0.01351,0.00000,0.0000,24.0,0.0,0.0,0.0,P162_18_172,NaN,0.0,3.0,68098.4,68098.4,68098.4,701247.30,40499.805,FO,NaN,NaN,0.0,12809.2,90.000,0.0,90.00000,90.000,114000.0,59773.715,0.0,50000.0,1.0,68098.4,780594500.0,-371.0,-371.0,-364.0,-7.0,8.0,NaN,-341.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64921.707,0.0,0.0,0.0,NaN,NaN,6191.600,34308.203,0.0,64921.707,0.0,0.0,0.0000,0.00,0.0000,0.00,NaN,NaN,121868.600,113980.0,0.0,0.0,64921.707,0.0,360.0,-7.0,-616.0,-371.0,-6.0,3.0,-6.0,NaN,NaN,NaN,NaN,14.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27500.0,27477.6,0.0,0.0,0.0,0.0,36800.0,-25541.0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

time: 10min 25s (started: 2024-04-07 10:07:30 -07:00)

In [17]:
df_train.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1526659 entries, 0 to 1526658
Data columns (total 348 columns):
 #    Column                               Non-Null Count    Dtype
---   ------                               --------------    -----
 0    case_id                              1526659 non-null  int32
 1    WEEK_NUM                             1526659 non-null  int32
 2    target                               1526659 non-null  int64
 3    month_decision                       1526659 non-null  int64
 4    day_decision                         1526659 non-null  int64
 5    assignmentdate_238D                  136996 non-null   float64
 6    assignmentdate_4527235D              114978 non-null   float64
 7    assignmentdate_4955616D              71633 non-null    float64
 8    birthdate_574D                       607871 non-null   float64
 9    contractssum_5085716L                157329 non-null   float64
 10   dateofbirth_337D                     1385691 non-null  float64
 11   dateofbirth_342D                     36500 non-null    float64
 12   days120_123L                         1385691 non-null  float64
 13   days180_256L                         1385691 non-null  float64
 14   days30_165L                          1385691 non-null  float64
 15   days360_512L                         1385691 non-null  float64
 16   days90_310L                          1385691 non-null  float64
 17   description_5085714M                 1500476 non-null  object
 18   education_1103M                      1500476 non-null  object
 19   education_88M                        1500476 non-null  object
 20   firstquarter_103L                    1385691 non-null  float64
 21   for3years_128L                       36514 non-null    float64
 22   for3years_504L                       36514 non-null    float64
 23   for3years_584L                       36514 non-null    float64
 24   formonth_118L                        36514 non-null    float64
 25   formonth_206L                        36514 non-null    float64
 26   formonth_535L                        36514 non-null    float64
 27   forquarter_1017L                     36514 non-null    float64
 28   forquarter_462L                      36514 non-null    float64
 29   forquarter_634L                      36514 non-null    float64
 30   fortoday_1092L                       36514 non-null    float64
 31   forweek_1077L                        36514 non-null    float64
 32   forweek_528L                         36514 non-null    float64
 33   forweek_601L                         36514 non-null    float64
 34   foryear_618L                         36514 non-null    float64
 35   foryear_818L                         36514 non-null    float64
 36   foryear_850L                         36514 non-null    float64
 37   fourthquarter_440L                   1385691 non-null  float64
 38   maritalst_385M                       1500476 non-null  object
 39   maritalst_893M                       1500476 non-null  object
 40   numberofqueries_373L                 1385691 non-null  float64
 41   pmtaverage_3A                        143589 non-null   float64
 42   pmtaverage_4527227A                  114978 non-null   float64
 43   pmtaverage_4955615A                  71845 non-null    float64
 44   pmtcount_4527229L                    114978 non-null   float64
 45   pmtcount_4955617L                    71845 non-null    float64
 46   pmtcount_693L                        146406 non-null   float64
 47   pmtscount_423L                       572638 non-null   float64
 48   pmtssum_45A                          572638 non-null   float64
 49   requesttype_4525192L                 673264 non-null   object
 50   responsedate_1012D                   720000 non-null   float64
 51   responsedate_4527233D                660327 non-null   float64
 52   responsedate_4917613D                224912 non-null   float64
 53   riskassesment_302T                   53559 non-null    object
 54   riskassesment_940T                   53560 non-null    float64
 55   secondquarter_766L                   1385691 non-null  float64
 56   thirdquarter_1082L                   1385691 non-null  float64
 57   actualdpdtolerance_344P              1108481 non-null  float64
 58   amtinstpaidbefduel24m_4187115A       965535 non-null   float64
 59   annuity_780A                         1526659 non-null  float64
 60   annuitynextmonth_57A                 1526655 non-null  float64
 61   applicationcnt_361L                  1526659 non-null  float64
 62   applications30d_658L                 1526659 non-null  float64
 63   applicationscnt_1086L                1526659 non-null  float64
 64   applicationscnt_464L                 1526659 non-null  float64
 65   applicationscnt_629L                 1526659 non-null  float64
 66   applicationscnt_867L                 1526659 non-null  float64
 67   avgdbddpdlast24m_3658932P            913457 non-null   float64
 68   avgdbddpdlast3m_4187120P             578415 non-null   float64
 69   avgdbdtollast24m_4525197P            553832 non-null   float64
 70   avgdpdtolclosure24_3658938P          1059484 non-null  float64
 71   avginstallast24m_3658937A            901784 non-null   float64
 72   avglnamtstart24m_4525187A            162509 non-null   float64
 73   avgmaxdpdlast9m_3716943P             769653 non-null   float64
 74   avgoutstandbalancel6m_4187114A       685478 non-null   float64
 75   avgpmtlast12m_4525200A               499672 non-null   float64
 76   bankacctype_710L                     417030 non-null   object
 77   cardtype_51L                         191691 non-null   object
 78   clientscnt12m_3712952L               1526659 non-null  float64
 79   clientscnt3m_3712950L                1526659 non-null  float64
 80   clientscnt6m_3712949L                1526659 non-null  float64
 81   clientscnt_100L                      1526659 non-null  float64
 82   clientscnt_1022L                     1526659 non-null  float64
 83   clientscnt_1071L                     1526659 non-null  float64
 84   clientscnt_1130L                     1526659 non-null  float64
 85   clientscnt_136L                      417 non-null      float64
 86   clientscnt_157L                      1526659 non-null  float64
 87   clientscnt_257L                      1526659 non-null  float64
 88   clientscnt_304L                      1526659 non-null  float64
 89   clientscnt_360L                      1526659 non-null  float64
 90   clientscnt_493L                      1526659 non-null  float64
 91   clientscnt_533L                      1526659 non-null  float64
 92   clientscnt_887L                      1526659 non-null  float64
 93   clientscnt_946L                      1526659 non-null  float64
 94   cntincpaycont9m_3716944L             1071469 non-null  float64
 95   cntpmts24_3658933L                   1065837 non-null  float64
 96   commnoinclast6m_3546845L             1183284 non-null  float64
 97   credamount_770A                      1526659 non-null  float64
 98   credtype_322L                        1526658 non-null  object
 99   currdebt_22A                         1526655 non-null  float64
 100  currdebtcredtyperange_828A           1526655 non-null  float64
 101  datefirstoffer_1144D                 692924 non-null   float64
 102  datelastinstal40dpd_247D             133818 non-null   float64
 103  datelastunpaid_3546854D              639000 non-null   float64
 104  daysoverduetolerancedd_3976961L      1074065 non-null  float64
 105  deferredmnthsnum_166L                1526659 non-null  float64
 106  disbursedcredamount_1113A            1526659 non-null  float64
 107  disbursementtype_67L                 1525793 non-null  object
 108  downpmt_116A                         1526659 non-null  float64
 109  dtlastpmtallstes_4499206D            549540 non-null   float64
 110  eir_270L                             1335826 non-null  float64
 111  equalitydataagreement_891L           78027 non-null    object
 112  equalityempfrom_62L                  37812 non-null    object
 113  firstclxcampaign_1125D               667445 non-null   float64
 114  firstdatedue_489D                    1044556 non-null  float64
 115  homephncnt_628L                      1526659 non-null  float64
 116  inittransactionamount_650A           192302 non-null   float64
 117  inittransactioncode_186L             1526658 non-null  object
 118  interestrate_311L                    1335826 non-null  float64
 119  interestrategrace_34L                20883 non-null    float64
 120  isbidproduct_1095L                   1526659 non-null  bool
 121  isbidproductrequest_292L             12458 non-null    object
 122  isdebitcard_729L                     192302 non-null   object
 123  lastactivateddate_801D               1073072 non-null  float64
 124  lastapplicationdate_877D             1221522 non-null  float64
 125  lastapprcommoditycat_1041M           1526659 non-null  object
 126  lastapprcommoditytypec_5251766M      1526659 non-null  object
 127  lastapprcredamount_781A              1084618 non-null  float64
 128  lastapprdate_640D                    1084618 non-null  float64
 129  lastcancelreason_561M                1526659 non-null  object
 130  lastdelinqdate_224D                  548684 non-null   float64
 131  lastdependentsnum_448L               29517 non-null    float64
 132  lastotherinc_902A                    3056 non-null     float64
 133  lastotherlnsexpense_631A             3058 non-null     float64
 134  lastrejectcommoditycat_161M          1526659 non-null  object
 135  lastrejectcommodtypec_5251769M       1526659 non-null  object
 136  lastrejectcredamount_222A            757613 non-null   float64
 137  lastrejectdate_50D                   757613 non-null   float64
 138  lastrejectreason_759M                1526659 non-null  object
 139  lastrejectreasonclient_4145040M      1526659 non-null  object
 140  lastrepayingdate_696D                2377 non-null     float64
 141  lastst_736L                          1221522 non-null  object
 142  maininc_215A                         1015404 non-null  float64
 143  mastercontrelectronic_519L           1220640 non-null  float64
 144  mastercontrexist_109L                1220640 non-null  float64
 145  maxannuity_159A                      1220640 non-null  float64
 146  maxannuity_4075009A                  75933 non-null    float64
 147  maxdbddpdlast1m_3658939P             565706 non-null   float64
 148  maxdbddpdtollast12m_3658940P         821155 non-null   float64
 149  maxdbddpdtollast6m_4187119P          650383 non-null   float64
 150  maxdebt4_972A                        1220640 non-null  float64
 151  maxdpdfrom6mto36m_3546853P           1183284 non-null  float64
 152  maxdpdinstldate_3546855D             700659 non-null   float64
 153  maxdpdinstlnum_3546846P              697257 non-null   float64
 154  maxdpdlast12m_727P                   1220640 non-null  float64
 155  maxdpdlast24m_143P                   1220640 non-null  float64
 156  maxdpdlast3m_392P                    1220640 non-null  float64
 157  maxdpdlast6m_474P                    1220640 non-null  float64
 158  maxdpdlast9m_1059P                   1220640 non-null  float64
 159  maxdpdtolerance_374P                 1220640 non-null  float64
 160  maxinstallast24m_3658928A            901784 non-null   float64
 161  maxlnamtstart6m_4525199A             493803 non-null   float64
 162  maxoutstandbalancel12m_4187113A      759701 non-null   float64
 163  maxpmtlast3m_4525190A                397329 non-null   float64
 164  mindbddpdlast24m_3658935P            913457 non-null   float64
 165  mindbdtollast24m_4525191P            553832 non-null   float64
 166  mobilephncnt_593L                    1526659 non-null  float64
 167  monthsannuity_845L                   1074066 non-null  float64
 168  numactivecreds_622L                  1526659 non-null  float64
 169  numactivecredschannel_414L           1526659 non-null  float64
 170  numactiverelcontr_750L               1526659 non-null  float64
 171  numcontrs3months_479L                1526659 non-null  float64
 172  numincomingpmts_3546848L             1071578 non-null  float64
 173  numinstlallpaidearly3d_817L          1080990 non-null  float64
 174  numinstls_657L                       1526655 non-null  float64
 175  numinstlsallpaid_934L                1080990 non-null  float64
 176  numinstlswithdpd10_728L              1070164 non-null  float64
 177  numinstlswithdpd5_4187116L           965535 non-null   float64
 178  numinstlswithoutdpd_562L             1070164 non-null  float64
 179  numinstmatpaidtearly2d_4499204L      679468 non-null   float64
 180  numinstpaid_4499208L                 679468 non-null   float64
 181  numinstpaidearly3d_3546850L          1079676 non-null  float64
 182  numinstpaidearly3dest_4493216L       686013 non-null   float64
 183  numinstpaidearly5d_1087L             1074066 non-null  float64
 184  numinstpaidearly5dest_4493211L       686013 non-null   float64
 185  numinstpaidearly5dobd_4499205L       679468 non-null   float64
 186  numinstpaidearly_338L                1074066 non-null  float64
 187  numinstpaidearlyest_4493214L         686013 non-null   float64
 188  numinstpaidlastcontr_4325080L        857473 non-null   float64
 189  numinstpaidlate1d_3546852L           1074066 non-null  float64
 190  numinstregularpaid_973L              1071047 non-null  float64
 191  numinstregularpaidest_4493210L       686013 non-null   float64
 192  numinsttopaygr_769L                  1074065 non-null  float64
 193  numinsttopaygrest_4493213L           686013 non-null   float64
 194  numinstunpaidmax_3546851L            1074065 non-null  float64
 195  numinstunpaidmaxest_4493212L         686013 non-null   float64
 196  numnotactivated_1143L                1526659 non-null  float64
 197  numpmtchanneldd_318L                 1526659 non-null  float64
 198  numrejects9m_859L                    1526659 non-null  float64
 199  opencred_647L                        1221522 non-null  object
 200  paytype1st_925L                      1468084 non-null  object
 201  paytype_783L                         1468084 non-null  object
 202  payvacationpostpone_4187118D         9329 non-null     float64
 203  pctinstlsallpaidearl3d_427L          1067921 non-null  float64
 204  pctinstlsallpaidlat10d_839L          1065297 non-null  float64
 205  pctinstlsallpaidlate1d_3546856L      1067921 non-null  float64
 206  pctinstlsallpaidlate4d_3546849L      1066832 non-null  float64
 207  pctinstlsallpaidlate6d_3546844L      1066580 non-null  float64
 208  pmtnum_254L                          1481705 non-null  float64
 209  posfpd10lastmonth_333P               1448133 non-null  float64
 210  posfpd30lastmonth_3976960P           1394771 non-null  float64
 211  posfstqpd30lastmonth_3976962P        1345537 non-null  float64
 212  previouscontdistrict_112M            1526659 non-null  object
 213  price_1097A                          1303419 non-null  float64
 214  sellerplacecnt_915L                  1526659 non-null  float64
 215  sellerplacescnt_216L                 1526659 non-null  float64
 216  sumoutstandtotal_3546847A            1081339 non-null  float64
 217  sumoutstandtotalest_4493215A         686013 non-null   float64
 218  totaldebt_9A                         1526656 non-null  float64
 219  totalsettled_863A                    1526655 non-null  float64
 220  totinstallast1m_4525188A             352448 non-null   float64
 221  twobodfilling_608L                   1526568 non-null  object
 222  typesuite_864L                       405154 non-null   object
 223  validfrom_1069D                      151773 non-null   float64
 224  max_actualdpd_943P                   1221356 non-null  float64
 225  max_annuity_853A                     1217886 non-null  float64
 226  max_credacc_actualbalance_314A       253572 non-null   float64
 227  max_credacc_credlmt_575A             1219184 non-null  float64
 228  max_credacc_maxhisbal_375A           253572 non-null   float64
 229  max_credacc_minhisbal_90A            253572 non-null   float64
 230  max_credamount_590A                  1219184 non-null  float64
 231  max_currdebt_94A                     1107643 non-null  float64
 232  max_downpmt_134A                     1219184 non-null  float64
 233  max_mainoccupationinc_437A           1220150 non-null  float64
 234  max_maxdpdtolerance_577P             1075682 non-null  float64
 235  max_outstandingdebt_522A             1106266 non-null  float64
 236  max_revolvingaccount_394A            253576 non-null   float64
 237  max_approvaldate_319D                1083651 non-null  float64
 238  max_creationdate_885D                1221373 non-null  float64
 239  max_dateactivated_425D               1071973 non-null  float64
 240  max_dtlastpmt_581D                   822816 non-null   float64
 241  max_dtlastpmtallstes_3545839D        977669 non-null   float64
 242  max_employedfrom_700D                967485 non-null   float64
 243  max_firstnonzeroinstldate_307D       1191765 non-null  float64
 244  max_num_group1                       1221373 non-null  float64
 245  max_amount_4527230A                  457934 non-null   float64
 246  max_recorddate_4527225D              457934 non-null   float64
 247  max_num_group1_3                     457934 non-null   float64
 248  max_amount_4917619A                  150732 non-null   float64
 249  max_deductiondate_4917603D           150732 non-null   float64
 250  max_num_group1_4                     150732 non-null   float64
 251  max_pmtamount_36A                    482265 non-null   float64
 252  max_processingdate_168D              482265 non-null   float64
 253  max_num_group1_5                     482265 non-null   float64
 254  max_credlmt_230A                     488255 non-null   float64
 255  max_credlmt_935A                     920776 non-null   float64
 256  max_debtoutstand_525A                1381312 non-null  float64
 257  max_debtoverdue_47A                  1381312 non-null  float64
 258  max_dpdmax_139P                      1259687 non-null  float64
 259  max_dpdmax_757P                      1009583 non-null  float64
 260  max_instlamount_768A                 916867 non-null   float64
 261  max_instlamount_852A                 389283 non-null   float64
 262  max_monthlyinstlamount_332A          1259620 non-null  float64
 263  max_monthlyinstlamount_674A          1006142 non-null  float64
 264  max_outstandingamount_354A           977784 non-null   float64
 265  max_outstandingamount_362A           887750 non-null   float64
 266  max_overdueamount_31A                1011001 non-null  float64
 267  max_overdueamount_659A               1259682 non-null  float64
 268  max_overdueamountmax2_14A            1260199 non-null  float64
 269  max_overdueamountmax2_398A           1011061 non-null  float64
 270  max_overdueamountmax_155A            1260199 non-null  float64
 271  max_overdueamountmax_35A             1009666 non-null  float64
 272  max_residualamount_488A              485611 non-null   float64
 273  max_residualamount_856A              916887 non-null   float64
 274  max_totalamount_6A                   977814 non-null   float64
 275  max_totalamount_996A                 887755 non-null   float64
 276  max_totaldebtoverduevalue_178A       1260199 non-null  float64
 277  max_totaldebtoverduevalue_718A       1225709 non-null  float64
 278  max_totaloutstanddebtvalue_39A       1260199 non-null  float64
 279  max_totaloutstanddebtvalue_668A      1225709 non-null  float64
 280  max_dateofcredend_289D               1260199 non-null  float64
 281  max_dateofcredend_353D               1011061 non-null  float64
 282  max_dateofcredstart_181D             1011061 non-null  float64
 283  max_dateofcredstart_739D             1260199 non-null  float64
 284  max_dateofrealrepmt_138D             1010690 non-null  float64
 285  max_lastupdate_1112D                 1260199 non-null  float64

In [25]:
#create data
import datetime

datetime_object = pd.to_datetime(["1/1/2018", np.datetime64("2018-01-08"), datetime.datetime(2018, 2, 1), pd.NaT])
#datetime_object = pd.to_datetime(["1/1/2018", np.datetime64("2018-01-08"), datetime.datetime(2018, 2, 1)])
df_dates=pd.DataFrame(datetime_object, columns=['date'])
df_dates

        date
0 2018-01-01
1 2018-01-08
2 2018-02-01
3        NaT

time: 9.18 ms (started: 2024-04-07 10:30:18 -07:00)

In [27]:
# Convert 'date_column' to datetime type if it's not already
df_dates['date'] = pd.to_datetime(df_dates['date'])


df_dates['month'] = df_dates['date'].dt.month
df_dates['day'] = df_dates['date'].dt.day

print(df_dates)

        date  month  day
0 2018-01-01    1.0  1.0
1 2018-01-08    1.0  8.0
2 2018-02-01    2.0  1.0
3        NaT    NaN  NaN
time: 8.35 ms (started: 2024-04-07 10:30:41 -07:00)

In [ ]:
type1='timedelta64[D]' #days
type2= #dt.days() #day of the month

## Overhaul 4: to_datetime()??

In [30]:
class Pipeline:
    @staticmethod
    def set_table_dtypes(df):
        for col in df.columns:
            if col in ["case_id", "WEEK_NUM", "num_group1", "num_group2"]:
                df.loc[:, col] = df.loc[:, col].astype('int32')
            elif col in ["date_decision"]:
                df.loc[:, col] = pd.to_datetime(df.loc[:, col]) #.astype('datetime64[ns]') #with_columns(pl.col(col).cast(pl.Date))
            elif col[-1] in ("P", "A"):
                df.loc[:, col] = df.loc[:, col].astype('float64') #with_columns(pl.col(col).cast(pl.Float64))
            elif col[-1] in ("M",):
                df.loc[:, col] = df.loc[:, col].astype('object') #.astype('string') #with_columns(pl.col(col).cast(pl.String))
            elif col[-1] in ("D",):
                df.loc[:, col] = pd.to_datetime(df.loc[:, col]) #.astype('datetime64[ns]') #with_columns(pl.col(col).cast(pl.Date))            

        return df
    
    @staticmethod
    def handle_dates(df):
        '''Edit date to number of days before the loan approval/refusal/denial decision date'''
        for col in df.columns:
            if col[-1] in ("D",):
                df.loc[:, col] = df.loc[:, col] - df.loc[:, 'date_decision'] #.with_columns(pl.col(col) - pl.col("date_decision"))
                df.loc[:, col] = df.loc[:, col].astype('timedelta64[D]') #df = df.with_columns(pl.col(col).dt.total_days())
                #with_columns(pl.col(col).cast(pl.Float32))
                
        return df.drop(columns=["date_decision", "MONTH"])

    
    @staticmethod
    def filter_cols(df):
        for col in df.columns:
            if col not in ["target", "case_id", "WEEK_NUM"]:
                isnull = df[col].isnull().mean()

                if isnull > 0.95:
                    df = df.drop(columns=col)

        for col in df.columns:
            if (col not in ["target", "case_id", "WEEK_NUM"]) & (df[col].dtype == object):
                freq = df[col].nunique()

                if (freq == 1) | (freq > 200):
                    df = df.drop(columns=col)

        return df



class Aggregator:
    @staticmethod
    def num_expr(df):
        '''P is for Transform DPD (Days past due); A is for Transform amount'''
        cols = [col for col in df.columns if col[-1] in ("P", "A")]

        return {col:'max' for col in cols}
   

    @staticmethod
    def date_expr(df):
        '''D is for Transform date'''
        cols = [col for col in df.columns if col[-1] in ("D",)]

        return {col:'max' for col in cols}

    @staticmethod
    def str_expr(df):
        '''M is for  Masking categories'''
        cols = [col for col in df.columns if col[-1] in ("M",)]
        
        return {col:'max' for col in cols}

    @staticmethod
    def other_expr(df):
        '''T is for Unspecified Transform'''
        cols = [col for col in df.columns if col[-1] in ("T")]
        
        return {col:'max' for col in cols}
    
    @staticmethod
    def other_expr2(df):
        '''L is for Unspecified Transform'''
        cols = [col for col in df.columns if col[-1] in ("L")]

        return {col:'max' for col in cols}


    
    @staticmethod
    def count_expr(df):
        cols = [col for col in df.columns if "num_group" in col]

        return {col:'max' for col in cols}
        

    @staticmethod
    def get_exprs(df):
        return {**Aggregator.num_expr(df),
                **Aggregator.date_expr(df), 
                #**Aggregator.str_expr(df), 
                #**Aggregator.other_expr(df),
                #**Aggregator.other_expr2(df),
                **Aggregator.count_expr(df)}

    
    @staticmethod    
    def get_cols_dictionary(df):
        exprs = Aggregator.get_exprs(df)
        cols = exprs.keys()
        cols_dictionary = {f'{col}':f'{exprs[col]}_{col}' for col in cols}
        print(f"cols_dictionary: {cols_dictionary}")
        return cols_dictionary

    
    

def read_file(path, depth=None):
    '''read in the file; the data type by column name or suffix'''
    df = pd.read_csv(path)
    df = df.pipe(Pipeline.set_table_dtypes)
    
    if depth in [1, 2]:
        df = df.groupby("case_id").agg(Aggregator.get_exprs(df)).rename(columns=Aggregator.get_cols_dictionary(df)) #df = df.groupby("case_id").agg(Aggregator.get_exprs(df))
    
    return df


def read_files(regex_path, depth=None):
    chunks = []
    for path in glob(str(regex_path)):
        df = pd.read_csv(path)
        df = df.pipe(Pipeline.set_table_dtypes)
        
        if depth in [1, 2]:
            df = df.groupby("case_id").agg(Aggregator.get_exprs(df)).rename(columns=Aggregator.get_cols_dictionary(df))

        
        chunks.append(df)
        
    df = pd.concat(chunks, axis=0)
    return df.drop_duplicates()





def feature_engineering(df_base, depth_0, depth_1, depth_2):
    
    #add 2 new columns
    df_base.loc[:, 'date_decision'] = pd.to_datetime(df_base.loc[:, 'date_decision'])
    df_base.loc[:, 'month_decision'] = df_base.loc[:, 'date_decision'].dt.month
    df_base.loc[:, 'day_decision'] = df_base.loc[:, 'date_decision'].dt.day
    #df_base = (df_base.with_columns(month_decision = pl.col("date_decision").dt.month(), weekday_decision = pl.col("date_decision").dt.weekday(),))

    
    #left join the DataFrame's in the list on 'case_id'
    for i, df in enumerate(depth_0 + depth_1 + depth_2):
        df_base = pd.merge(df_base, df, on='case_id', how='left', suffixes=("", f"_{i}")) #df_base = df_base.join(df, how="left", on="case_id", suffix=f"_{i}")
        
    df_base = df_base.pipe(Pipeline.handle_dates)
    
    return df_base




TRAIN_DIR = "../data/raw/train/"

data_store = {
    "df_base": read_file(TRAIN_DIR + "train_base.csv"),
    "depth_0": [
        read_file(TRAIN_DIR + "train_static_cb_0.csv"),
        read_files(TRAIN_DIR + "train_static_0_*.csv"),
    ],
    "depth_1": [
        read_files(TRAIN_DIR + "train_applprev_1_*.csv", 1),
        read_file(TRAIN_DIR + "train_tax_registry_a_1.csv", 1),
        read_file(TRAIN_DIR + "train_tax_registry_b_1.csv", 1),
        read_file(TRAIN_DIR + "train_tax_registry_c_1.csv", 1),
        read_files(TRAIN_DIR + "train_credit_bureau_a_1_*.csv", 1),
        read_file(TRAIN_DIR + "train_credit_bureau_b_1.csv", 1),
        read_file(TRAIN_DIR + "train_other_1.csv", 1),
        read_file(TRAIN_DIR + "train_person_1.csv", 1),
        read_file(TRAIN_DIR + "train_deposit_1.csv", 1),
        read_file(TRAIN_DIR + "train_debitcard_1.csv", 1),
    ],
    "depth_2": [
        read_file(TRAIN_DIR + "train_credit_bureau_b_2.csv", 2),
        read_files(TRAIN_DIR + "train_credit_bureau_a_2_*.csv", 2),
    ]
}



def preview_df(df):
    """Of this DataFrame, prints the row and column count and then returns the concatenated first 5 and last % rows.

    Args:
        df (DataFrame): This pandas DataFrame object.
    Returns:
        df (DataFrame): The concatenated first 5 and last 5 rows of this pandas DataFrame.
    """
    if df.shape[0] > 9:
        print(df.shape)
        return pd.DataFrame(pd.concat([df.head(5), df.tail(5)]))
    else:
        return df

    
#The *args will give you all positional arguments as a tuple
#The **kwargs will give you all keyword arguments as a dictionary

df_train = feature_engineering(**data_store)



preview_df(df_train)

/var/folders/77/y4hv4_s9751293nzv4yrfrtm0000gn/T/ipykernel_4499/787695804.py:118: DtypeWarning: Columns (1,2,3,4,7,45,46,47,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/77/y4hv4_s9751293nzv4yrfrtm0000gn/T/ipykernel_4499/787695804.py:130: DtypeWarning: Columns (20,45,46,56,57,84,143,146,167) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/77/y4hv4_s9751293nzv4yrfrtm0000gn/T/ipykernel_4499/787695804.py:130: DtypeWarning: Columns (20,45,46,53,57,84,143,146,167) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/77/y4hv4_s9751293nzv4yrfrtm0000gn/T/ipykernel_4499/787695804.py:130: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

TypeError: '>=' not supported between instances of 'str' and 'float'

time: 1min 7s (started: 2024-04-07 10:47:46 -07:00)

In [ ]:
#^--- inspect what the column for suffix "L" are???

In [14]:




TRAIN_DIR = "../data/raw/train/"
#df = read_files2(TRAIN_DIR + "train_applprev_1_0.csv", 1)
df = read_files2(TRAIN_DIR + "train_applprev_1_*.csv", 1)
preview_df(df)

NameError: name 'read_files2' is not defined

time: 327 ms (started: 2024-04-06 22:30:37 -07:00)

In [ ]:
def preview_df(df):
    """Of this DataFrame, prints the row and column count and then returns the concatenated first 5 and last % rows.

    Args:
        df (DataFrame): This pandas DataFrame object.
    Returns:
        df (DataFrame): The concatenated first 5 and last 5 rows of this pandas DataFrame.
    """
    if df.shape[0] > 9:
        print(df.shape)
        return pd.DataFrame(pd.concat([df.head(5), df.tail(5)]))
    else:
        return df

preview_df(df)

In [ ]:


df_train_tax_registry_a_1=pd.read_csv(TRAIN_DIR + "train_tax_registry_a_1.csv")

preview_df(df_train_tax_registry_a_1)

In [ ]:


def read_files3(regex_path, depth=None):
    chunks = []
    for path in glob(str(regex_path)):
        df = pd.read_csv(path)
        df = df.pipe(Pipeline.set_table_dtypes)
        
        if depth in [1, 2]:
#             print(print(f"df.shape: {df.shape}"))
#             print(f"df: {df}")
#             print(f"len(Aggregator.get_exprs(df)): {len(Aggregator.get_exprs(df))}")
#             print(f"Aggregator.get_exprs(df): {Aggregator.get_exprs(df)}")
#             print(f"len(Aggregator.get_cols_dictionary(df)): {len(Aggregator.get_cols_dictionary(df))}")
#             print(f"Aggregator.get_cols_dictionary(df): {Aggregator.get_cols_dictionary(df)}")
            df = df.groupby("case_id").agg('max')#.rename(columns=Aggregator.get_cols_dictionary(df))
        
        chunks.append(df)
        
    df = pd.concat(chunks, axis=0) #pl.concat(chunks, how="vertical_relaxed")
    df = df.drop_duplicates()
    #df = df.unique(subset=["case_id"])
    
    return df

In [ ]:
df_train_tax_registry_a_1=pd.read_csv(TRAIN_DIR + "train_tax_registry_a_1.csv")

preview_df(df_train_tax_registry_a_1)

In [ ]:
df_train_tax_registry_a_1.info()

In [ ]:
#add 2 new columns
df_base.loc[:, 'date_decision'] = pd.to_datetime(df_base.loc[:, 'date_decision'])
df_base.loc[:, 'month_decision'] = df_base.loc[:, 'date_decision'].dt.month
df_base.loc[:, 'day_decision'] = df_base.loc[:, 'date_decision'].dt.day
#df_base = (df_base.with_columns(month_decision = pl.col("date_decision").dt.month(), weekday_decision = pl.col("date_decision").dt.weekday(),))


#left join the DataFrame's in the list on 'case_id'
for i, df in enumerate(depth_0 + depth_1 + depth_2):
    df_base = pd.merge(df_base, df, on='case_id', how='left', suffix=f"_{i}") #df_base = df_base.join(df, how="left", on="case_id", suffix=f"_{i}")

df_base = df_base.pipe(Pipeline.handle_dates)

return df_base

In [ ]:

df_train_tax_registry_a_1=pd.read_csv(TRAIN_DIR + "train_tax_registry_a_1.csv")

preview_df(df_train_tax_registry_a_1)

In [ ]:
df = df.pipe(Pipeline.set_table_dtypes)

    if depth in [1, 2]:
        df = df.groupby("case_id").agg('max')

    chunks.append(df)

df = pd.concat(chunks, axis=0)
df = df.drop_duplicates()

In [ ]:
df_train_tax_registry_a_1.info()

In [ ]:

df_collection={}

#Read in Feature Definitions as a DataFrame
key='feature_definitions'
relative_filename_path=os.path.join("..", "data", "raw", str(key)+".csv")
df_collection[key]=pd.read_csv(relative_filename_path)

#Filter for Select (i.e. 'train_applprev_1_0') features
print(df_collection[key].shape)
df_collection[key]

### Feature Elimination

In [ ]:
df_train = df_train.pipe(Pipeline.filter_cols)

print("train data shape:\t", df_train.shape)

### Garbage Collection

In [ ]:
del data_store

gc.collect()

### EDA

In [ ]:
print("Train is duplicated:\t", df_train["case_id"].duplicated().any())
print("Train Week Range:\t", (df_train["WEEK_NUM"].min(), df_train["WEEK_NUM"].max()))

In [ ]:
sns.lineplot(
    data=df_train,
    x="WEEK_NUM",
    y="target",
)
plt.show()

### Training

In [ ]:
X = df_train.drop(columns=["target", "case_id", "WEEK_NUM"])
y = df_train["target"]
weeks = df_train["WEEK_NUM"]

cv = StratifiedGroupKFold(n_splits=5, shuffle=False)

params = {
    "boosting_type": "gbdt",
    "objective": "binary",
    "metric": "auc",
    "max_depth": 8,
    "learning_rate": 0.05,
    "n_estimators": 1000,
    "colsample_bytree": 0.8, 
    "colsample_bynode": 0.8,
    "verbose": -1,
    "random_state": 42,
    "device": "gpu",
}

fitted_models = []

for idx_train, idx_valid in cv.split(X, y, groups=weeks):
    X_train, y_train = X.iloc[idx_train], y.iloc[idx_train]
    X_valid, y_valid = X.iloc[idx_valid], y.iloc[idx_valid]

    model = lgb.LGBMClassifier(**params)
    model.fit(
        X_train, y_train,
        eval_set=[(X_valid, y_valid)],
        callbacks=[lgb.log_evaluation(100), lgb.early_stopping(100)]
    )

    fitted_models.append(model)

model = VotingModel(fitted_models)

### Prediction

### Submission

### Appendix

In [28]:
import os
import pandas as pd
df_collection={}

#Read in Feature Definitions as a DataFrame
key='feature_definitions'
relative_filename_path=os.path.join("..", "data", "raw", str(key)+".csv")
df_collection[key]=pd.read_csv(relative_filename_path)

#Filter for Select (i.e. 'train_applprev_1_0') features
print(df_collection[key].shape)
df_collection[key]

(465, 2)

,Variable,Description
0,actualdpd_943P,Days Past Due (DPD) of previous contract (actual).
1,actualdpdtolerance_344P,DPD of client with tolerance.
2,addres_district_368M,District of the person's address.
3,addres_role_871L,Role of person's address.
4,addres_zip_823M,Zip code of the address.
5,amount_1115A,Credit amount of the active contract provided by the credit bureau.
6,amount_416A,Deposit amount.
7,amount_4527230A,Tax deductions amount tracked by the government registry.
8,amount_4917619A,Tax deductions amount tracked by the government registry.
9,amtdebitincoming_4809443A,Incoming debit card transactions amount.
10,amtdebitoutgoing_4809440A,Outgoing debit card transactions amount.
11,amtdepositbalance_4809441A,Deposit balance of client.
12,amtdepositincoming_4809444A,Amount of incoming deposits to client's account.
13,amtdepositoutgoing_4809442A,Amount of outgoing deposits from client's account.
14,amtinstpaidbefduel24m_4187115A,Number of instalments paid before due date in the last 24 months.
15,annualeffectiverate_199L,Interest rate of the closed contracts.
16,annualeffectiverate_63L,Interest rate for the active contracts.
17,annuity_780A,Monthly annuity amount.
18,annuity_853A,Monthly annuity for previous applications.
19,annuitynextmonth_57A,Next month's amount of annuity.
20,applicationcnt_361L,Number of applications associated with the same email address as the client.
21,applications30d_658L,Number of applications made by the client in the last 30 days.
22,applicationscnt_1086L,Number of applications associated with the same phone number.
23,applicationscnt_464L,Number of applications made in the last 30 days by other clients with the same employer as the applicant.
24,applicationscnt_629L,Number of applications with the same employer in the last 7 days.
25,applicationscnt_867L,Number of applications associated with the same mobile phone.
26,approvaldate_319D,Approval Date of Previous Application
27,assignmentdate_238D,Tax authority data - date of assignment.
28,assignmentdate_4527235D,Tax authority data - Date of assignment.
29,assignmentdate_4955616D,Tax authority assignment date.
30,avgdbddpdlast24m_3658932P,Average days past or before due of payment during the last 24 months.
31,avgdbddpdlast3m_4187120P,Average days past or before due of payment during the last 3 months.
32,avgdbdtollast24m_4525197P,Average days of payment before due date within the last 24 months (with tolerance).
33,avgdpdtolclosure24_3658938P,"Average DPD (days past due) with tolerance within the past 24 months from the maximum closure date, assuming that the contract is finished. If the contract is ongoing, the calculation is based on the current date."
34,avginstallast24m_3658937A,Average instalments paid by the client over the past 24 months.
35,avglnamtstart24m_4525187A,Average loan amount in the last 24 months.
36,avgmaxdpdlast9m_3716943P,Average Days Past Due (DPD) of the client in last 9 months.
37,avgoutstandbalancel6m_4187114A,Average outstanding balance of applicant for the last 6 months.
38,avgpmtlast12m_4525200A,Average of payments made by the client in the last 12 months.
39,bankacctype_710L,Type of applicant's bank account.
40,birth_259D,Date of birth of the person.
41,birthdate_574D,Client's date of birth (credit bureau data).
42,birthdate_87D,Birth date of the person.
43,byoccupationinc_3656910L,Applicant's income from previous applications.
44,cacccardblochreas_147M,Card blocking reason.
45,cancelreason_3545846M,Application cancellation reason.
46,cardtype_51L,Type of credit card.
47,childnum_185L,Number of children of the applicant.
48,childnum_21L,Number of children in the previous application.
49,classificationofcontr_1114M,Classificiation of the active contract.
50,classificationofcontr_13M,Classificiation of the active contract.
51,classificationofcontr_400M,Classificiation of the closed contract.
52,clientscnt_100L,Number of applications with matching employer's phone and client's.
53,clientscnt_1022L,Number of clients sharing the same mobile phone.
54,clientscnt_1071L,Number of applications where the alternative phone number matches that of the client.
55,clientscnt_1130L,Number of applications where client's phone number matches the alternative phone contact.
56,clientscnt_136L,Number of applications associated with same email address as client's email.
57,clientscnt_157L,Number of clients whose employer has the same phone number as the client.
58,clientscnt_257L,Number of clients that share an alternative phone number with the applicant.
59,clientscnt_304L,Number of clients with the same phone number.
60,clientscnt_360L,Number of clients that have the same alternative phone number and employer's phone number.
61,clientscnt_493L,Number of clients with matching phone numbers for both the employer and the client.
62,clientscnt_533L,Number of clients with same client's and alternative's phone number
63,clientscnt_887L,Number of clients sharing the same employer's phone number.
64,clientscnt_946L,Number of clients with matching mobile and employer's number.
65,clientscnt12m_3712952L,Number of clients that have used the same mobile phone as the applicant in the past 12 months.
66,clientscnt3m_3712950L,Number of clients who have the same mobile phone number in the last 3 months.
67,clientscnt6m_3712949L,Total number of clients who have used the same mobile number in the last 6 months.
68,cntincpaycont9m_3716944L,Number of incoming payments in the past 9 months.
69,cntpmts24_3658933L,Number of months with any incoming payment in last 24 months.
70,collater_typofvalofguarant_298M,Collateral valuation type (active contract).
71,collater_typofvalofguarant_407M,Collateral valuation type (closed contract).
72,collater_valueofguarantee_1124L,Value of collateral for active contract.
73,collater_valueofguarantee_876L,Value of collateral for closed contract.
74,collaterals_typeofguarante_359M,Type of collateral that was used as a guarantee for a closed contract.
75,collaterals_typeofguarante_669M,Collateral type for the active contract.
76,commnoinclast6m_3546845L,Number of communications indicating low income in the last six months.
77,contaddr_district_15M,Zip code of a contact person's address.
78,contaddr_matchlist_1032L,Indicates whether the contact address is found in a code list.
79,contaddr_smempladdr_334L,Indicates whether the contact address is the same as the employment address.
80,contaddr_zipcode_807M,Zip code of contact address.
81,contractdate_551D,Contract date of the active contract
82,contractenddate_991D,End date of deposit contract.
83,contractmaturitydate_151D,End date of active contract.
84,contractssum_5085716L,Total sum of values of contracts retrieved from external credit bureau.
85,contractst_516M,Contract status.
86,contractst_545M,Contract status.
87,contractst_964M,Contract status of terminated credit contract.
88,contractsum_5085717L,Sum of other contract values.
89,contracttype_653M,Contract Type
90,conts_role_79M,Type of contact role of a person.
91,conts_type_509L,Person contact type in previous application.
92,creationdate_885D,Date when previous application was created.
93,credacc_actualbalance_314A,Actual balance on credit account.
94,credacc_cards_status_52L,Card status of the previous credit account.
95,credacc_credlmt_575A,Credit card credit limit provided for previous applications.
96,credacc_maxhisbal_375A,Maximal historical balance of previous credit account
97,credacc_minhisbal_90A,Minimum historical balance of previous credit accounts.
98,credacc_status_367L,Account status of previous credit applications.
99,credacc_transactions_402L,Number of transactions made with the previous credit account of the applicant.
100,credamount_590A,Loan amount or card limit of previous applications.
101,credamount_770A,Loan amount or credit card limit.
102,credlmt_1052A,Credit limit of an active loan.
103,credlmt_228A,Credit limit for closed loans.
104,credlmt_230A,Credit limit of the closed credit contracts from credit bureau.
105,credlmt_3940954A,Credit limit for active loan.
106,credlmt_935A,Credit limit for active loan.
107,credor_3940957M,Creditor's name
108,credquantity_1099L,Number of credits in credit bureau
109,credquantity_984L,Number of closed credits in credit bureau.
110,credtype_322L,Type of credit.
111,credtype_587L,Credit type of previous application.
112,currdebt_22A,Current debt amount of the client.
113,currdebt_94A,Previous application's current debt.
114,currdebtcredtyperange_828A,Current amount of debt of the applicant.
115,dateactivated_425D,Contract activation date of the applicant's previous application.
116,datefirstoffer_1144D,Date of first customer relationship management (CRM) offer.
117,datelastinstal40dpd_247D,Date of last instalment that was more than 40 days past due (DPD).
118,datelastunpaid_3546854D,Date of the last unpaid instalment.
119,dateofbirth_337D,Client's date of birth.
120,dateofbirth_342D,Client's date of birth.
121,dateofcredend_289D,End date of an active credit contract.
122,dateofcredend_353D,End date of a closed credit contract.
123,dateofcredstart_181D,Date when the credit contract was closed.
124,dateofcredstart_739D,Start date of a closed credit contract.
125,dateofrealrepmt_138D,Date of credit's closure (contract termination date).
126,days120_123L,Number of credit bureau queries for the last 120 days.
127,days180_256L,Number of credit bureau queries for last 180 days.
128,days30_165L,Number of credit bureau queries for the last 30 days.
129,days360_512L,Number of Credit Bureau queries for last 360 days.
130,days90_310L,Number of credit bureau queries for the last 90 days.
131,daysoverduetolerancedd_3976961L,Number of days that past after the due date (with tolerance).
132,debtoutstand_525A,Outstanding amount of existing contract.
133,debtoverdue_47A,Amount that is currently past due on a client's existing credit contract.
134,debtpastduevalue_732A,Amount of unpaid debt for existing contracts.
135,debtvalue_227A,Outstanding amount for existing debt contracts.
136,deductiondate_4917603D,Tax deduction date.
137,deferredmnthsnum_166L,Number of deferred months.
138,description_351M,Categorization of clients by credit bureau.
139,description_5085714M,Categorization of clients by credit bureau.
140,disbursedcredamount_1113A,Disbursed credit amount after consolidation.
141,disbursementtype_67L,Type of disbursement.
142,district_544M,District of the address used in the previous loan application.
143,downpmt_116A,Amount of downpayment.
144,downpmt_134A,Previous application downpayment amount.
145,dpd_550P,The number of days past due for active loans where a guarantee has been provided.
146,dpd_733P,Days past due (DPD) for guaranteed loans that were terminated according to credit bureau data.
147,dpdmax_139P,Maximal days past due for active contract.
148,dpdmax_757P,Maximum days past due for a closed contract.
149,dpdmax_851P,Maximal past due days for active contracts in the credit bureau.
150,dpdmaxdatemonth_442T,Max DPD occurrence month for terminated contracts from credit bureau data.
151,dpdmaxdatemonth_804T,Month when the maximum Day Past Due (DPD) occurred for active contracts on credit bureau's records.
152,dpdmaxdatemonth_89T,Month when maximum days past due occurred on the active contract with the credit bureau.
153,dpdmaxdateyear_596T,Year when maximum Days Past Due (DPD) occurred for the active contract.
154,dpdmaxdateyear_742T,Year of the maximum Days Past Due (DPD) on an active credit contract in the credit bureau.
155,dpdmaxdateyear_896T,Year of maximum Days Past Due of closed contract obtained from Credit Bureau.
156,dtlastpmt_581D,Date of last payment made by the applicant.
157,dtlastpmtallstes_3545839D,Date of the applicant's last payment.
158,dtlastpmtallstes_4499206D,Date of last payment made by the applicant.
159,education_1103M,Level of education of the client provided by external source.
160,education_1138M,Applicant's education level from their previous application.
161,education_88M,Education level of the client.
162,education_927M,Education level of the person.
163,eir_270L,Interest rate.
164,empl_employedfrom_271D,Start date of employment.
165,empl_employedtotal_800L,Employment length of a person.
166,empl_industry_691L,Employment Industry of the person.
167,empladdr_district_926M,District where the employer's address is located.
168,empladdr_zipcode_114M,Zipcode of employer's address.
169,employedfrom_700D,Employment start date from the previous application.
170,employername_160M,Employer's name.
171,empls_economicalst_849M,"The economical status of the person (num_group1 - person, num_group2 - employment)."
172,empls_employedfrom_796D,"Start of employment (num_group1 - person, num_group2 - employment)."
173,empls_employer_name_740M,"Employer's name (num_group1 - person, num_group2 - employment)."
174,equalitydataagreement_891L,"Flag indicating sudden changes in client's social-demographic data (e.g. education, family status, housing type)."
175,equalityempfrom_62L,Flag indicating a sudden change in the client's length of employment.
176,familystate_447L,Family state of the person.
177,familystate_726L,Family State in previous application of applicant.
178,financialinstitution_382M,Name of financial institution that is linked to a closed contract.
179,financialinstitution_591M,Financial institution name of the active contract.
180,firstclxcampaign_1125D,Date of the client's first campaign.
181,firstdatedue_489D,Date of the first due date.
182,firstnonzeroinstldate_307D,Date of first instalment in the previous application.
183,firstquarter_103L,Number of results obtained from credit bureau in the first quarter.
184,for3years_128L,Number of rejected applications in the past 3 years.
185,for3years_504L,Client's credit history data over the last three years.
186,for3years_584L,Number of cancellations in the last 3 years.
187,formonth_118L,Number of rejections in a month.
188,formonth_206L,Number of cancelations in the previous month.
189,formonth_535L,Credit history for the last month.
190,forquarter_1017L,Number of cancellations recorded in the credit bureau in the last quarter.
191,forquarter_462L,Number of credit applications that were rejected in the last quarter.
192,forquarter_634L,Credit history for the last quarter.
193,fortoday_1092L,Client's credit history for today.
194,forweek_1077L,Number of cancelations in the last week.
195,forweek_528L,Credit history for the last week.
196,forweek_601L,Number of rejected applications in the last week.
197,foryear_618L,Number of application rejections in the previous year.
198,foryear_818L,Number of cancelations that occurred in last year.
199,foryear_850L,Credit history for the last year.
200,fourthquarter_440L,Number of results in fourth quarter.
201,gender_992L,Gender of a person.
202,homephncnt_628L,Number of distinct home phones on client's application.
203,housetype_905L,House type of the person.
204,housingtype_772L,Type of housing of the person.
205,incometype_1044T,Type of income of the person
206,inittransactionamount_650A,Initial transaction amount of the credit application.
207,inittransactioncode_186L,Transaction type of the initial credit transaction.
208,inittransactioncode_279L,Type of the initial transaction made in the previous application of the client.
209,installmentamount_644A,Instalment amount of a closed and secured credit contract.
210,installmentamount_833A,Instalment amount for a secured and active contract in credit bureau.
211,instlamount_768A,Instalment amount for the active contract in credit bureau.
212,instlamount_852A,Instalment amount for closed contract.
213,instlamount_892A,Instalment amount for active credit contract.
214,interesteffectiverate_369L,Interest rate on active contract.
215,interestrate_311L,The interest rate of the active credit contract.
216,interestrate_508L,Interest rate for a closed contract in the credit bureau.
217,interestrategrace_34L,Interest rate during the grace period.
218,interestrateyearly_538L,Annual interest rate for existing contract obtained from credit bureau.
219,isbidproduct_1095L,Flag indicating if the product is a cross-sell.
220,isbidproduct_390L,Flag for determining if the product is a cross-sell in previous applications.
221,isbidproductrequest_292L,Flag indicating if the product is a cross-sell.
222,isdebitcard_527L,Previous application flag indicating if product being applied for is a debit card.
223,isdebitcard_729L,Flag indicating if the product is a debit card.
224,isreference_387L,Flag indicating whether the person is a reference contact.
225,language1_981M,The primary language of the person.
226,last180dayaveragebalance_704A,Average balance on debit card in the last 180 days.
227,last180dayturnover_1134A,Debit card's turnover within the last 180 days.
228,last30dayturnover_651A,Debit card turnover for the last 30 days.
229,lastactivateddate_801D,Contract activation date for previous applications.
230,lastapplicationdate_877D,Date of previous customer's application.
231,lastapprcommoditycat_1041M,Commodity category of the last loan applications made by the applicant.
232,lastapprcommoditytypec_5251766M,Commodity type of the last application.
233,lastapprcredamount_781A,Credit amount from the client's last application.
234,lastapprdate_640D,Date of approval on client's most recent previous application.
235,lastcancelreason_561M,Cancellation reason of the last application.
236,lastdelinqdate_224D,Date of the last delinquency occurrence.
237,lastdependentsnum_448L,Number of dependents in the client's last loan application.
238,lastotherinc_902A,Amount of other income reported by the client in their last application.
239,lastotherlnsexpense_631A,Monthly expenses on other loans from the last application.
240,lastrejectcommoditycat_161M,Category of commodity in the applicant's last rejected application.
241,lastrejectcommodtypec_5251769M,Commodity type of the last rejected application.
242,lastrejectcredamount_222A,Credit amount on last rejected application.
243,lastrejectdate_50D,Date of most recent rejected application by the applicant.
244,lastrejectreason_759M,Reason for rejection on the most recent rejected application.
245,lastrejectreasonclient_4145040M,Reason for the client's last loan rejection.
246,lastrepayingdate_696D,Date of the last payment made by the applicant.
247,lastst_736L,Status of the client's previous credit application.
248,lastupdate_1112D,Date of last update for an active contract from credit bureau.
249,lastupdate_260D,Last update date for the active contracts.
250,lastupdate_388D,Date of last update for a closed contract in the credit bureau.
251,maininc_215A,Client's primary income amount.
252,mainoccupationinc_384A,Amount of the main income of the client.
253,mainoccupationinc_437A,Client's main income amount in their previous application.
254,maritalst_385M,Marital status of the client.
255,maritalst_703L,Marital status of the client.
256,maritalst_893M,Marital status of the client
257,mastercontrelectronic_519L,Flag indicating the existence of the master contract for the client.
258,mastercontrexist_109L,Flag indicating whether or not the applicant has an existing master contract.
259,maxannuity_159A,Maximum annuity previously obtained by client.
260,maxannuity_4075009A,Maximal annuity offered to the client in the current application.
261,maxdbddpdlast1m_3658939P,Maximum number of days past due in the last month. A negative value indicates the number of days before the due date.
262,maxdbddpdtollast12m_3658940P,Maximum number of days past due in last 12 months. A negative value implies days before due date.
263,maxdbddpdtollast6m_4187119P,Maximum number of days past due in last 6 months. This predictor takes the value as a negative number when it represents days before due date.
264,maxdebt4_972A,Maximal principal debt of the client in the history older than 4 months.
265,maxdebtpduevalodued_3940955A,Days past due at the time of the maximum debt.

time: 57.5 ms (started: 2024-04-07 10:39:23 -07:00)